#ifndef TETRIS_BKGRND_LVL_3_HPP
#define TETRIS_BKGRND_LVL_3_HPP

#include <array>
#include "common/utilities.hpp"
#include "../tetris_defs.hpp"

namespace tetris {

inline constexpr std::array TETRIS_BKGRND_LVL_3 { embp::pfold(
BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,YELLOW,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,MAGENTA,BLUE,BLUE,BLUE,
BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,YELLOW,BLUE,GREEN,MAGENTA,BLUE,BLUE,RED,BLUE,BLUE,MAGENTA,BLUE,BLUE,BLUE,BLUE,
BLUE,BLUE,BLUE,BLUE,BLUE,YELLOW,BLUE,BLUE,MAGENTA,GREEN,BLUE,BLUE,BLUE,RED,MAGENTA,BLUE,BLUE,BLUE,BLUE,BLUE,
BLUE,BLUE,BLACK,YELLOW,YELLOW,BLUE,BLUE,MAGENTA,BLUE,BLUE,GREEN,BLUE,YELLOW,MAGENTA,RED,RED,BLUE,BLUE,BLUE,BLUE,
BLUE,BLUE,YELLOW,BLUE,BLUE,BLUE,MAGENTA,RED,BLUE,BLUE,BLUE,GREEN,BLUE,BLUE,BLUE,BLUE,RED,BLUE,YELLOW,BLUE,
BLUE,YELLOW,BLUE,BLUE,BLUE,MAGENTA,BLUE,BLUE,RED,BLUE,YELLOW,MAGENTA,GREEN,BLUE,BLUE,BLUE,BLUE,YELLOW,BLUE,BLUE,
YELLOW,BLUE,BLUE,BLUE,MAGENTA,BLUE,BLUE,BLUE,BLUE,RED,MAGENTA,BLUE,BLUE,GREEN,BLUE,BLUE,YELLOW,BLUE,BLUE,BLUE,
BLUE,BLUE,BLUE,MAGENTA,BLUE,BLUE,BLUE,YELLOW,YELLOW,BLUE,RED,BLUE,BLUE,BLUE,YELLOW,YELLOW,BLUE,BLUE,BLUE,BLUE,
BLUE,BLUE,RED,BLUE,BLUE,BLUE,BLUE,YELLOW,MAGENTA,BLUE,BLUE,RED,BLUE,YELLOW,BLUE,GREEN,BLUE,BLUE,BLUE,BLUE,
BLUE,BLUE,BLUE,RED,BLUE,BLUE,YELLOW,BLUE,BLUE,BLUE,BLUE,BLUE,YELLOW,BLUE,BLUE,BLUE,GREEN,BLUE,BLUE,BLUE,
BLUE,BLUE,BLUE,BLUE,RED,YELLOW,MAGENTA,BLUE,BLUE,BLUE,BLUE,YELLOW,RED,BLUE,BLUE,BLUE,BLUE,GREEN,MAGENTA,BLUE,
BLUE,BLUE,BLUE,BLUE,BLUE,RED,BLUE,BLUE,BLUE,GREEN,YELLOW,BLUE,BLUE,RED,BLUE,BLUE,BLUE,BLACK,BLUE,BLUE,
BLUE,BLUE,GREEN,BLUE,BLUE,BLUE,RED,BLUE,BLUE,BLUE,GREEN,BLUE,BLUE,BLUE,RED,MAGENTA,MAGENTA,BLUE,BLUE,BLUE,
BLACK,BLUE,GREEN,BLUE,BLUE,BLUE,BLUE,RED,BLUE,BLUE,BLUE,GREEN,BLUE,BLUE,MAGENTA,BLUE,BLUE,BLUE,BLUE,BLACK,
BLUE,BLUE,BLUE,GREEN,BLUE,BLUE,BLUE,BLUE,RED,BLUE,BLUE,BLUE,GREEN,MAGENTA,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,
BLUE,BLACK,BLUE,BLUE,GREEN,BLUE,YELLOW,BLUE,BLUE,RED,BLUE,BLUE,MAGENTA,YELLOW,GREEN,BLUE,BLUE,BLACK,BLUE,BLUE,
BLUE,BLUE,BLUE,BLUE,BLUE,YELLOW,BLUE,BLUE,BLUE,BLUE,RED,BLUE,YELLOW,BLUE,BLUE,GREEN,BLUE,BLUE,BLACK,MAGENTA,
BLUE,BLUE,BLUE,BLUE,YELLOW,BLUE,GREEN,BLUE,BLUE,BLUE,BLUE,RED,BLUE,BLUE,BLUE,BLUE,GREEN,MAGENTA,BLUE,BLACK,
BLUE,BLUE,BLUE,YELLOW,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,YELLOW,BLUE,BLUE,BLUE,BLUE,BLUE,MAGENTA,BLUE,BLUE,BLUE,
BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,MAGENTA,BLUE,BLUE
)};

inline constexpr screen::Tile TETRIS_BKGRND_LVL_3_TILE {
    .side_length = 20,
    .format = VIDEO_FORMAT,
    .data = std::data(TETRIS_BKGRND_LVL_3)
};

} // namespace tetris
#endif
