#ifndef TETRIS_BKGRND_LVL_7_HPP
#define TETRIS_BKGRND_LVL_7_HPP

#include <array>
#include "common/utilities.hpp"
#include "../tetris_defs.hpp"

namespace tetris {

inline constexpr std::array TETRIS_BKGRND_LVL_7 { embp::pfold(
CYAN,CYAN,GREEN,GREEN,YELLOW,BLUE,GREEN,GREEN,GREEN,MAGENTA,MAGENTA,YELLOW,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,CYAN,
YELLOW,RED,BLACK,CYAN,YELLOW,BLACK,BLUE,CYAN,CYAN,CYAN,CYAN,BLUE,YELLOW,YELLOW,MAGENTA,MAGENTA,MAGENTA,BLACK,BLACK,BLACK,
BLACK,RED,BLACK,BLACK,CYAN,CYAN,BLUE,BLACK,MAGENTA,BLACK,BLACK,GREEN,BLACK,YELLOW,BLACK,BLACK,BLACK,MAGENTA,BLACK,YELLOW,
BLACK,RED,BLACK,BLACK,CYAN,CYAN,GREEN,BLUE,MAGENTA,BLACK,BLACK,GREEN,BLACK,BLACK,YELLOW,BLACK,BLACK,MAGENTA,YELLOW,BLACK,
BLACK,BLACK,CYAN,CYAN,MAGENTA,MAGENTA,CYAN,BLACK,GREEN,BLUE,BLACK,BLUE,BLACK,BLACK,YELLOW,YELLOW,BLACK,MAGENTA,YELLOW,BLACK,
MAGENTA,CYAN,BLACK,GREEN,BLUE,RED,BLACK,CYAN,BLACK,BLUE,GREEN,BLUE,GREEN,BLACK,BLACK,YELLOW,YELLOW,BLACK,MAGENTA,BLACK,
BLACK,BLACK,BLACK,GREEN,BLACK,BLUE,RED,CYAN,BLACK,BLUE,BLUE,GREEN,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,BLACK,MAGENTA,
CYAN,BLACK,BLACK,BLACK,GREEN,BLACK,RED,BLACK,CYAN,CYAN,BLUE,BLACK,MAGENTA,BLACK,GREEN,BLACK,BLACK,MAGENTA,MAGENTA,BLACK,
CYAN,MAGENTA,RED,RED,RED,RED,BLUE,BLACK,BLUE,CYAN,CYAN,BLACK,MAGENTA,MAGENTA,GREEN,BLACK,BLACK,MAGENTA,BLACK,CYAN,
RED,MAGENTA,BLACK,BLACK,GREEN,BLACK,BLACK,BLUE,BLUE,MAGENTA,CYAN,MAGENTA,MAGENTA,MAGENTA,GREEN,BLACK,BLACK,MAGENTA,RED,CYAN,
BLACK,MAGENTA,BLACK,BLACK,GREEN,BLACK,BLACK,BLUE,MAGENTA,GREEN,BLACK,CYAN,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,BLACK,CYAN,
MAGENTA,MAGENTA,BLACK,BLACK,BLACK,GREEN,BLUE,MAGENTA,GREEN,BLACK,BLACK,BLACK,CYAN,GREEN,BLACK,BLACK,BLACK,RED,MAGENTA,CYAN,
BLACK,BLACK,BLACK,BLUE,BLUE,BLUE,BLACK,MAGENTA,BLACK,BLACK,BLACK,MAGENTA,GREEN,BLACK,CYAN,BLACK,BLACK,RED,BLACK,CYAN,
BLACK,BLACK,BLUE,BLUE,BLACK,BLACK,BLACK,MAGENTA,BLACK,BLACK,BLACK,MAGENTA,GREEN,BLACK,CYAN,BLACK,RED,BLACK,BLACK,CYAN,
BLACK,BLUE,BLACK,BLACK,BLACK,BLACK,BLACK,MAGENTA,BLACK,GREEN,GREEN,RED,RED,RED,CYAN,RED,BLACK,BLACK,CYAN,BLACK,
BLUE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,MAGENTA,BLACK,GREEN,RED,BLACK,BLACK,RED,CYAN,RED,BLACK,BLACK,CYAN,BLUE,
BLUE,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,MAGENTA,MAGENTA,RED,GREEN,BLACK,MAGENTA,MAGENTA,BLACK,BLACK,CYAN,CYAN,BLACK,BLUE,
BLACK,BLACK,YELLOW,BLUE,BLACK,GREEN,GREEN,BLACK,BLACK,MAGENTA,BLACK,GREEN,BLACK,MAGENTA,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,YELLOW,BLACK,BLACK,YELLOW,BLACK,BLACK,GREEN,GREEN,GREEN,MAGENTA,MAGENTA,MAGENTA,MAGENTA,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,YELLOW,BLACK,BLACK,BLUE,BLUE,BLACK,BLACK,BLACK,RED,MAGENTA,MAGENTA,BLACK,BLACK,BLACK,CYAN,BLACK,BLACK,CYAN,CYAN
)};

inline constexpr screen::Tile TETRIS_BKGRND_LVL_7_TILE {
    .side_length = 20,
    .format = VIDEO_FORMAT,
    .data = std::data(TETRIS_BKGRND_LVL_7)
};

} // namespace tetris
#endif
