#ifndef TETRIS_BKGRND_LVL_1_HPP
#define TETRIS_BKGRND_LVL_1_HPP

#include <array>
#include "common/utilities.hpp"
#include "../tetris_defs.hpp"

namespace tetris {

inline constexpr std::array TETRIS_BKGRND_LVL_1 { embp::pfold(
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,
WHITE,WHITE,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,LGREY,BLACK,
WHITE,RED,WHITE,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,LGREY,MAGENTA,BLACK,
WHITE,RED,RED,WHITE,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,LGREY,MAGENTA,MAGENTA,BLACK,
WHITE,RED,RED,RED,WHITE,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,LGREY,MAGENTA,MAGENTA,MAGENTA,BLACK,
WHITE,RED,RED,RED,RED,WHITE,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,LGREY,MAGENTA,MAGENTA,MAGENTA,MAGENTA,BLACK,
WHITE,RED,RED,RED,RED,RED,WHITE,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,LGREY,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,BLACK,
WHITE,RED,RED,RED,RED,RED,RED,WHITE,MAGENTA,MAGENTA,MAGENTA,MAGENTA,LGREY,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,BLACK,
WHITE,RED,RED,RED,RED,RED,RED,RED,WHITE,MAGENTA,MAGENTA,LGREY,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,BLACK,
WHITE,RED,RED,RED,RED,RED,RED,RED,RED,LGREY,LGREY,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,BLACK,
WHITE,RED,RED,RED,RED,RED,RED,RED,RED,LGREY,DRKGRY,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,BLACK,
WHITE,RED,RED,RED,RED,RED,RED,RED,LGREY,RED,RED,DRKGRY,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,BLACK,
WHITE,RED,RED,RED,RED,RED,RED,LGREY,RED,RED,RED,RED,DRKGRY,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,BLACK,
WHITE,RED,RED,RED,RED,RED,LGREY,RED,RED,RED,RED,RED,RED,DRKGRY,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,BLACK,
WHITE,RED,RED,RED,RED,LGREY,RED,RED,RED,RED,RED,RED,RED,RED,DRKGRY,MAGENTA,MAGENTA,MAGENTA,MAGENTA,BLACK,
WHITE,RED,RED,RED,LGREY,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,DRKGRY,MAGENTA,MAGENTA,MAGENTA,BLACK,
WHITE,RED,RED,LGREY,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,DRKGRY,MAGENTA,MAGENTA,BLACK,
WHITE,RED,LGREY,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,DRKGRY,MAGENTA,BLACK,
WHITE,LGREY,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,DRKGRY,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK
)};

inline constexpr screen::Tile TETRIS_BKGRND_LVL_1_TILE {
    .side_length = 20,
    .format = VIDEO_FORMAT,
    .data = std::data(TETRIS_BKGRND_LVL_1)
};

} // namespace tetris
#endif
