#ifndef TETRIS_BKGRND_LVL_4_HPP
#define TETRIS_BKGRND_LVL_4_HPP

#include <array>
#include "common/utilities.hpp"
#include "../tetris_defs.hpp"

namespace tetris {

inline constexpr std::array TETRIS_BKGRND_LVL_4 { embp::pfold(
LGREY,LGREY,RED,RED,BLUE,BLUE,BLUE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,RED,
LGREY,WHITE,RED,LGREY,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,RED,RED,RED,RED,RED,RED,RED,RED,RED,
LGREY,LGREY,LGREY,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,LGREY,RED,RED,RED,RED,RED,RED,RED,RED,
LGREY,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,LGREY,RED,RED,RED,RED,RED,RED,RED,
LGREY,LGREY,CYAN,CYAN,LGREY,LGREY,BLUE,BLUE,BLUE,BLUE,BLUE,LGREY,BLUE,LGREY,RED,RED,RED,RED,RED,RED,
LGREY,RED,CYAN,CYAN,CYAN,CYAN,LGREY,LGREY,LGREY,BLUE,LGREY,LGREY,LGREY,RED,RED,RED,RED,RED,RED,RED,
LGREY,RED,LGREY,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,YELLOW,YELLOW,LGREY,LGREY,LGREY,RED,RED,RED,RED,LGREY,MAGENTA,
LGREY,RED,MAGENTA,LGREY,CYAN,CYAN,CYAN,CYAN,LGREY,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLUE,BLUE,LGREY,LGREY,LGREY,MAGENTA,
MAGENTA,LGREY,MAGENTA,MAGENTA,CYAN,CYAN,CYAN,LGREY,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,BLUE,BLUE,BLUE,LGREY,MAGENTA,
MAGENTA,MAGENTA,MAGENTA,MAGENTA,LGREY,CYAN,LGREY,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,BLUE,MAGENTA,MAGENTA,MAGENTA,
MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,LGREY,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,MAGENTA,MAGENTA,MAGENTA,
MAGENTA,MAGENTA,MAGENTA,MAGENTA,LGREY,RED,YELLOW,YELLOW,YELLOW,LGREY,GREEN,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,LGREY,MAGENTA,MAGENTA,MAGENTA,
MAGENTA,MAGENTA,MAGENTA,MAGENTA,RED,RED,LGREY,YELLOW,YELLOW,GREEN,GREEN,GREEN,YELLOW,YELLOW,BLUE,BLUE,BLUE,LGREY,MAGENTA,MAGENTA,
MAGENTA,MAGENTA,MAGENTA,LGREY,RED,RED,RED,YELLOW,LGREY,GREEN,GREEN,GREEN,LGREY,LGREY,BLUE,BLUE,BLUE,LGREY,MAGENTA,MAGENTA,
MAGENTA,MAGENTA,LGREY,RED,RED,RED,RED,LGREY,GREEN,GREEN,GREEN,GREEN,LGREY,DRKGRY,BLUE,BLUE,BLUE,BLUE,BLUE,MAGENTA,
MAGENTA,LGREY,RED,RED,RED,RED,RED,BLUE,LGREY,GREEN,GREEN,GREEN,DRKGRY,DRKGRY,BLUE,BLUE,BLUE,BLUE,BLUE,LGREY,
LGREY,RED,RED,RED,RED,RED,LGREY,BLUE,BLUE,GREEN,GREEN,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,BLUE,LGREY,RED,RED,
LGREY,RED,RED,RED,RED,RED,BLUE,BLUE,BLUE,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,RED,RED,RED,
LGREY,RED,RED,RED,RED,LGREY,BLUE,BLUE,BLUE,YELLOW,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,CYAN,RED,RED,RED,
LGREY,RED,RED,RED,LGREY,BLUE,BLUE,LGREY,YELLOW,YELLOW,YELLOW,DRKGRY,DRKGRY,DRKGRY,CYAN,CYAN,CYAN,LGREY,RED,RED
)};

inline constexpr screen::Tile TETRIS_BKGRND_LVL_4_TILE {
    .side_length = 20,
    .format = VIDEO_FORMAT,
    .data = std::data(TETRIS_BKGRND_LVL_4)
};

} // namespace tetris
#endif
