#ifndef TETRIS_BKGRND_LVL_5_HPP
#define TETRIS_BKGRND_LVL_5_HPP

#include <array>
#include "common/utilities.hpp"
#include "../tetris_defs.hpp"

namespace tetris {

inline constexpr std::array TETRIS_BKGRND_LVL_5 { embp::pfold(
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,MAGENTA,MAGENTA,YELLOW,RED,RED,RED,RED,RED,YELLOW,YELLOW,MAGENTA,MAGENTA,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,MAGENTA,YELLOW,RED,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,RED,YELLOW,MAGENTA,BLACK,BLACK,BLACK,
BLACK,BLACK,MAGENTA,YELLOW,RED,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,RED,YELLOW,MAGENTA,BLACK,BLACK,
BLACK,MAGENTA,YELLOW,RED,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,RED,YELLOW,MAGENTA,BLACK,
BLACK,MAGENTA,RED,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,YELLOW,MAGENTA,BLACK,
BLACK,YELLOW,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,RED,RED,RED,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,RED,YELLOW,BLACK,
MAGENTA,RED,BLUE,BLUE,BLUE,BLUE,BLUE,RED,BLACK,BLACK,BLACK,RED,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,RED,MAGENTA,
MAGENTA,RED,BLUE,BLUE,BLUE,BLUE,RED,BLACK,BLACK,BLACK,BLACK,BLACK,RED,BLUE,BLUE,BLUE,BLUE,BLUE,RED,MAGENTA,
MAGENTA,RED,BLUE,BLUE,BLUE,BLUE,RED,BLACK,BLACK,BLACK,BLACK,BLACK,RED,BLUE,BLUE,BLUE,BLUE,BLUE,RED,MAGENTA,
MAGENTA,RED,BLUE,BLUE,BLUE,BLUE,RED,BLACK,BLACK,BLACK,BLACK,BLACK,RED,BLUE,BLUE,BLUE,BLUE,BLUE,RED,MAGENTA,
MAGENTA,RED,BLUE,BLUE,BLUE,BLUE,BLUE,RED,BLACK,BLACK,BLACK,RED,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,RED,MAGENTA,
BLACK,YELLOW,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,RED,RED,RED,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,RED,YELLOW,BLACK,
BLACK,YELLOW,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,RED,YELLOW,BLACK,
BLACK,MAGENTA,RED,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,YELLOW,MAGENTA,BLACK,
BLACK,MAGENTA,YELLOW,RED,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,RED,YELLOW,MAGENTA,BLACK,
BLACK,BLACK,MAGENTA,YELLOW,RED,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,RED,YELLOW,MAGENTA,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,YELLOW,YELLOW,RED,BLUE,BLUE,BLUE,BLUE,BLUE,RED,RED,YELLOW,YELLOW,MAGENTA,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,MAGENTA,MAGENTA,YELLOW,RED,RED,RED,RED,RED,YELLOW,YELLOW,MAGENTA,MAGENTA,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK
)};

inline constexpr screen::Tile TETRIS_BKGRND_LVL_5_TILE {
    .side_length = 20,
    .format = VIDEO_FORMAT,
    .data = std::data(TETRIS_BKGRND_LVL_5)
};

} // namespace tetris
#endif
