#ifndef TETRIS_BKGRND_LVL_2_HPP
#define TETRIS_BKGRND_LVL_2_HPP

#include <array>
#include "common/utilities.hpp"
#include "../tetris_defs.hpp"

namespace tetris {

inline constexpr std::array TETRIS_BKGRND_LVL_2 { embp::pfold(
LGREY,LGREY,BLACK,BLACK,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,LGREY,
LGREY,LGREY,BLACK,BLACK,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,LGREY,
LGREY,LGREY,BLACK,BLACK,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,BLACK,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,LGREY,
LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,LGREY,
LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,LGREY,
LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,LGREY,
LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,RED,RED,RED,RED,BLACK,BLACK,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,LGREY,
BLACK,BLACK,BLACK,BLACK,RED,RED,RED,RED,RED,RED,RED,RED,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,BLACK,
BLACK,BLACK,BLACK,BLACK,RED,RED,RED,RED,RED,RED,RED,RED,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,MAGENTA,BLACK,
BLACK,BLACK,BLACK,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLUE,BLACK,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,BLACK,BLACK,BLACK,BLACK,BLACK,BLUE,
BLUE,BLUE,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,BLACK,BLACK,BLACK,BLUE,BLUE,BLUE,
BLUE,BLUE,BLUE,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,BLACK,BLACK,BLACK,BLUE,BLUE,BLUE,
BLUE,BLUE,BLUE,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,BLACK,BLACK,BLACK,BLUE,BLUE,BLUE,
BLUE,BLUE,BLUE,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,BLACK,BLACK,BLACK,BLACK,BLUE,BLUE,BLUE,
BLUE,BLUE,BLACK,BLACK,RED,RED,RED,RED,RED,RED,RED,RED,BLACK,BLACK,BLACK,BLACK,BLACK,BLUE,BLUE,BLUE,
BLUE,BLACK,BLACK,BLACK,BLACK,RED,RED,RED,RED,RED,RED,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLUE,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,
LGREY,LGREY,BLACK,BLACK,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,LGREY
)};

inline constexpr screen::Tile TETRIS_BKGRND_LVL_2_TILE {
    .side_length = 20,
    .format = VIDEO_FORMAT,
    .data = std::data(TETRIS_BKGRND_LVL_2)
};

} // namespace tetris
#endif
