#include "wall.hpp"

#include "common/utilities.hpp"
#include "texture_defs.hpp"

#include <array>
#include <cstdint>

namespace chippie::chip
{
namespace
{
/* python tools/tetris_img_to_cpp.py images/chip_tile_24x24.png */
inline constexpr std::array tile_data{embp::pfold(
    WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE,
    WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, DRKGRY, WHITE, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY,
    LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, DRKGRY,
    WHITE, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, BLACK, DRKGRY, BLACK, LGREY, LGREY, BLACK, DRKGRY, BLACK,
    LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, DRKGRY, WHITE, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, BLACK,
    LGREY, LGREY, LGREY, BLACK, BLACK, LGREY, LGREY, LGREY, BLACK, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, DRKGRY,
    WHITE, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, LGREY, LGREY, LGREY, LGREY, DRKGRY,
    DRKGRY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, DRKGRY, WHITE, LGREY, LGREY, LGREY, LGREY, LGREY, DRKGRY, BLACK,
    LGREY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, BLACK, DRKGRY, LGREY, LGREY, LGREY, LGREY, LGREY, DRKGRY,
    WHITE, LGREY, LGREY, LGREY, LGREY, BLACK, DRKGRY, DRKGRY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY,
    DRKGRY, DRKGRY, DRKGRY, BLACK, LGREY, LGREY, LGREY, LGREY, DRKGRY, WHITE, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY,
    BLACK, LGREY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, BLACK, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY,
    DRKGRY, WHITE, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY,
    DRKGRY, DRKGRY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, DRKGRY, WHITE, LGREY, LGREY, LGREY, LGREY, LGREY, DRKGRY,
    BLACK, LGREY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, BLACK, DRKGRY, LGREY, LGREY, LGREY, LGREY, LGREY,
    DRKGRY, WHITE, LGREY, LGREY, LGREY, LGREY, BLACK, DRKGRY, DRKGRY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, DRKGRY,
    LGREY, DRKGRY, DRKGRY, DRKGRY, BLACK, LGREY, LGREY, LGREY, LGREY, DRKGRY, WHITE, LGREY, LGREY, LGREY, LGREY, LGREY,
    LGREY, BLACK, LGREY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, BLACK, LGREY, LGREY, LGREY, LGREY, LGREY,
    LGREY, DRKGRY, WHITE, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, DRKGRY,
    LGREY, DRKGRY, DRKGRY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, DRKGRY, WHITE, LGREY, LGREY, LGREY, LGREY, LGREY,
    DRKGRY, BLACK, LGREY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, BLACK, DRKGRY, LGREY, LGREY, LGREY, LGREY,
    LGREY, DRKGRY, WHITE, LGREY, LGREY, LGREY, LGREY, BLACK, DRKGRY, DRKGRY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY,
    DRKGRY, LGREY, DRKGRY, DRKGRY, DRKGRY, BLACK, LGREY, LGREY, LGREY, LGREY, DRKGRY, WHITE, LGREY, LGREY, LGREY, LGREY,
    LGREY, LGREY, BLACK, LGREY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, BLACK, LGREY, LGREY, LGREY, LGREY,
    LGREY, LGREY, DRKGRY, WHITE, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY,
    DRKGRY, LGREY, DRKGRY, DRKGRY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, DRKGRY, WHITE, LGREY, LGREY, LGREY, LGREY,
    LGREY, DRKGRY, BLACK, LGREY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, BLACK, DRKGRY, LGREY, LGREY, LGREY,
    LGREY, LGREY, DRKGRY, WHITE, LGREY, LGREY, LGREY, LGREY, BLACK, DRKGRY, DRKGRY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY,
    DRKGRY, LGREY, DRKGRY, DRKGRY, DRKGRY, BLACK, LGREY, LGREY, LGREY, LGREY, DRKGRY, WHITE, LGREY, LGREY, LGREY, LGREY,
    LGREY, LGREY, BLACK, LGREY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, DRKGRY, LGREY, BLACK, LGREY, LGREY, LGREY, LGREY,
    LGREY, LGREY, DRKGRY, WHITE, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, DRKGRY, BLACK, DRKGRY, BLACK, DRKGRY, BLACK,
    DRKGRY, BLACK, DRKGRY, BLACK, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, DRKGRY, WHITE, LGREY, LGREY, LGREY, LGREY,
    LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY,
    LGREY, LGREY, DRKGRY, WHITE, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY,
    LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY)};

inline constexpr screen::Tile tile{
    .side_length = TILE_SIDE_LENGTH, .transparent = 0, .format = TILE_SCREEN_FORMAT, .data = std::data(tile_data)};

} // namespace

screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::chip