#include "wall.hpp"

#include "common/utilities.hpp"
#include "texture_defs.hpp"

#include <array>
#include <cstdint>

namespace chippie::wall
{
namespace
{
/* python tetris_img_to_cpp.py images/wall_tile_24x24.png*/
inline constexpr std::array tile_data{embp::pfold(
    LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY,
    LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY,
    LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, LGREY, DRKGRY,
    LGREY, LGREY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, BLACK, LGREY, LGREY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, BLACK, DRKGRY, LGREY, LGREY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, BLACK,
    LGREY, LGREY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, BLACK, DRKGRY, LGREY, LGREY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, BLACK, LGREY, LGREY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, BLACK, DRKGRY,
    LGREY, LGREY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, BLACK, LGREY, LGREY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, BLACK, DRKGRY, LGREY, LGREY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, BLACK,
    LGREY, LGREY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, BLACK, DRKGRY, LGREY, LGREY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, BLACK, LGREY, LGREY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, BLACK, DRKGRY,
    LGREY, LGREY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, BLACK, LGREY, LGREY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, BLACK, DRKGRY, LGREY, LGREY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, BLACK,
    LGREY, LGREY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, BLACK, DRKGRY, LGREY, LGREY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, BLACK, LGREY, LGREY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, BLACK, DRKGRY,
    LGREY, LGREY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, BLACK, LGREY, LGREY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY, DRKGRY,
    DRKGRY, DRKGRY, DRKGRY, BLACK, DRKGRY, LGREY, LGREY, DRKGRY, BLACK, DRKGRY, BLACK, DRKGRY, BLACK, DRKGRY, BLACK,
    DRKGRY, BLACK, DRKGRY, BLACK, DRKGRY, BLACK, DRKGRY, BLACK, DRKGRY, BLACK, DRKGRY, BLACK, DRKGRY, BLACK, LGREY,
    DRKGRY, BLACK, DRKGRY, BLACK, DRKGRY, BLACK, DRKGRY, BLACK, DRKGRY, BLACK, DRKGRY, BLACK, DRKGRY, BLACK, DRKGRY,
    BLACK, DRKGRY, BLACK, DRKGRY, BLACK, DRKGRY, BLACK, DRKGRY)};

constexpr screen::Tile tile{
    .side_length = TILE_SIDE_LENGTH, .transparent = 0, .format = TILE_SCREEN_FORMAT, .data = std::data(tile_data)};

} // namespace

screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::wall