/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_133_HPP
#define CHIPPIE_LEVEL_133_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_133
{
    void load_level(state&) noexcept;
}
#endif
