/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_111_HPP
#define CHIPPIE_LEVEL_111_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_111
{
    void load_level(state&) noexcept;
}
#endif
