/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_119_HPP
#define CHIPPIE_LEVEL_119_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_119
{
    void load_level(state&) noexcept;
}
#endif
