/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_139_HPP
#define CHIPPIE_LEVEL_139_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_139
{
    void load_level(state&) noexcept;
}
#endif
