/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_149_HPP
#define CHIPPIE_LEVEL_149_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_149
{
    void load_level(state&) noexcept;
}
#endif
