/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_33_HPP
#define CHIPPIE_LEVEL_33_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_33
{
    void load_level(state&) noexcept;
}
#endif
