/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_132_HPP
#define CHIPPIE_LEVEL_132_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_132
{
    void load_level(state&) noexcept;
}
#endif
