/* AUTO GENERATED BY process_map_image.py */
#include "level.hpp"

#include <cmath>
#include <array>
#include <cstdint>

#include "level_1.hpp"
#include "level_2.hpp"
#include "level_3.hpp"
#include "level_4.hpp"
#include "level_5.hpp"
#include "level_6.hpp"
#include "level_7.hpp"
#include "level_8.hpp"
#include "level_9.hpp"
#include "level_10.hpp"
#include "level_11.hpp"
#include "level_12.hpp"
#include "level_13.hpp"

namespace chippie
{

namespace
{

constexpr std::array jump_table {
    level_1::load_level,
    level_2::load_level,
    level_3::load_level,
    level_4::load_level,
    level_5::load_level,
    level_6::load_level,
    level_7::load_level,
    level_8::load_level,
    level_9::load_level,
    level_10::load_level,
    level_11::load_level,
    level_12::load_level,
    level_13::load_level,
};

}

namespace level
{
uint32_t get_max_level() noexcept
{
    return std::size(jump_table);
}

void load(state& game_state, uint32_t level) noexcept
{
    level = std::min(static_cast<uint32_t>(std::size(jump_table)), std::max(uint32_t{1U}, level));
    jump_table[level - 1](game_state);
}
}
}
