/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_100_HPP
#define CHIPPIE_LEVEL_100_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_100
{
    void load_level(state&) noexcept;
}
#endif
