/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_35_HPP
#define CHIPPIE_LEVEL_35_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_35
{
    void load_level(state&) noexcept;
}
#endif
