/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_55_HPP
#define CHIPPIE_LEVEL_55_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_55
{
    void load_level(state&) noexcept;
}
#endif
