/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_101_HPP
#define CHIPPIE_LEVEL_101_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_101
{
    void load_level(state&) noexcept;
}
#endif
