/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_77_HPP
#define CHIPPIE_LEVEL_77_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_77
{
    void load_level(state&) noexcept;
}
#endif
