/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_36_HPP
#define CHIPPIE_LEVEL_36_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_36
{
    void load_level(state&) noexcept;
}
#endif
