/* AUTO GENERATED BY process_map_image.py */
#include "level_128.hpp"
#include "chippie/entities/entities.hpp"
#include <cstring>

namespace chippie::level_128
{
namespace
{
    constexpr int TIME_REMAINING{ 0 };
    constexpr int CHIPS_REMAINING{ 0 };
    constexpr const char* HINT_TEXT{ nullptr };
    constexpr const char* LEVEL_NAME_TEXT{ nullptr };
#error "Just a friendly reminder to fill in time remaining, chips remaining, etc :)"

    /* clang-format off */
    constexpr std::array DATA
    {
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::YELLOW_DOOR, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::YELLOW_DOOR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::SOCKET, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::PORTAL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::YELLOW_DOOR, terrain_type::WALL, terrain_type::FLIPPERS, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::YELLOW_DOOR, terrain_type::WALL, terrain_type::RED_BUTTON, terrain_type::WALL, terrain_type::WATER, terrain_type::WALL, terrain_type::CLONER_PURPLE_BALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::THIEF, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WATER, terrain_type::WALL, terrain_type::RED_BUTTON, terrain_type::CLEAR, terrain_type::WALL, terrain_type::GRAVEL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::GRAVEL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLONER_PURPLE_BALL, terrain_type::CLEAR, terrain_type::YELLOW_KEY, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::SUCTION_BOOTS, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::YELLOW_DOOR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::RED_BUTTON, terrain_type::WALL, terrain_type::CLONER_CENTIPEDE, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::THIEF, terrain_type::CHIP, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_DOWN, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::FIRE_BOOTS, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_DOWN, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::FIRE, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::PUSH_FLOOR_DOWN, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_DOWN, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::FIRE, terrain_type::WALL, terrain_type::CLEAR, terrain_type::YELLOW_KEY, terrain_type::WALL, terrain_type::CHIP, terrain_type::PUSH_FLOOR_LEFT, terrain_type::PUSH_FLOOR_LEFT, terrain_type::PUSH_FLOOR_LEFT, terrain_type::PUSH_FLOOR_LEFT, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::PUSH_FLOOR_DOWN, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::GRAVEL, terrain_type::RED_BUTTON, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::PUSH_FLOOR_DOWN, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLONER_FIRE_DANCER, terrain_type::GREEN_BUTTON_CLEAR, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::CLEAR, terrain_type::GRAVEL, terrain_type::PUSH_FLOOR_LEFT, terrain_type::PUSH_FLOOR_LEFT, terrain_type::PUSH_FLOOR_LEFT, terrain_type::CHIP, terrain_type::PUSH_FLOOR_LEFT, terrain_type::WALL_TRAP, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::FIRE, terrain_type::FIRE, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::GREEN_BUTTON, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::WATER, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::CHIP, terrain_type::FIRE, terrain_type::FIRE, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::FLIPPERS, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::PUSH_FLOOR_DOWN, terrain_type::FIRE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::FIRE, terrain_type::FIRE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::RED_BUTTON, terrain_type::WALL, terrain_type::GREEN_BUTTON_CLEAR, terrain_type::WALL, terrain_type::PUSH_FLOOR_UP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL_TRAP, terrain_type::PUSH_FLOOR_DOWN, terrain_type::FIRE, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::CHIP, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::GRAVEL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CHIP, terrain_type::CHIP, terrain_type::CHIP, terrain_type::WALL, terrain_type::PUSH_FLOOR_DOWN, terrain_type::FIRE, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::CHIP, terrain_type::FIRE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::PUSH_FLOOR_UP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::PUSH_FLOOR_DOWN, terrain_type::FIRE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_UP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_LEFT, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::FIRE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::YELLOW_KEY, terrain_type::WATER, terrain_type::GREEN_BUTTON_CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GRAVEL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::WALL_TRAP, terrain_type::PUSH_FLOOR_LEFT, terrain_type::PUSH_FLOOR_LEFT, terrain_type::PUSH_FLOOR_LEFT, terrain_type::PUSH_FLOOR_LEFT, terrain_type::PUSH_FLOOR_LEFT, terrain_type::CHIP, terrain_type::FIRE, terrain_type::FIRE, terrain_type::PUSH_FLOOR_UP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_LEFT, terrain_type::FIRE, terrain_type::FIRE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::YELLOW_KEY, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::PUSH_FLOOR_DOWN, terrain_type::FIRE, terrain_type::PUSH_FLOOR_UP, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_LEFT, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLONER_FIRE_DANCER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GRAVEL, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::CHIP, terrain_type::WALL, terrain_type::YELLOW_KEY, terrain_type::FIRE, terrain_type::GREEN_BUTTON_CLEAR, terrain_type::PUSH_FLOOR_LEFT, terrain_type::PUSH_FLOOR_LEFT, terrain_type::PUSH_FLOOR_LEFT, terrain_type::PUSH_FLOOR_UP, terrain_type::FIRE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_LEFT, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
    };
    /* clang-format on */

void load_level_from_rom_stub(state &game_state) noexcept
{
    /* set the time limit, if any */
    game_state.time_remaining = TIME_REMAINING;
    game_state.countdown_timer.reset();

    /* set the amount of chips for the level */
    game_state.chippie_inventory.set(inventory_item::CHIPS, CHIPS_REMAINING);

    /* set the hint string, which can be null */
    game_state.hint_text = HINT_TEXT;
    /* set the level name */
    game_state.level_name_text = LEVEL_NAME_TEXT;

    /* load the map data */
    std::memcpy(std::data(game_state.the_map.map_data), std::data(DATA), std::size(DATA) * sizeof(terrain_type));
}

void load_entity_list_from_rom_stub(state &game_state) noexcept
{
    game_state.entity_list.clear();
    uint8_t uuid = 0;

    // by convention, Chippie is always the first one in the entity_list
    game_state.entity_list.push_back(create_entity(entity_type::CHIPPIE, {.x = 15, .y = 12}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 11, .y = 1}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::WATER_GLIDER, {.x = 23, .y = 8}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::CENTIPEDE, {.x = 22, .y = 10}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::CENTIPEDE, {.x = 20, .y = 11}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::FIRE_DANCER, {.x = 2, .y = 17}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::FIRE_DANCER, {.x = 4, .y = 17}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::FIRE_DANCER, {.x = 6, .y = 17}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::FIRE_DANCER, {.x = 21, .y = 17}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::FIRE_DANCER, {.x = 22, .y = 18}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::FIRE_DANCER, {.x = 4, .y = 19}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::FIRE_DANCER, {.x = 23, .y = 19}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::FIRE_DANCER, {.x = 24, .y = 20}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 16, .y = 24}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::FIRE_DANCER, {.x = 2, .y = 25}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::FIRE_DANCER, {.x = 4, .y = 25}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::FIRE_DANCER, {.x = 6, .y = 25}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 13, .y = 26}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 11, .y = 28}, direction::UP, uuid++, game_state));
    static_assert(decltype(game_state.entity_list){}.capacity() >= 19);
    game_state.red_button_list.push_back(red_button{
        .button = {.x = 13, .y = 13},
        .clone_spawn = {.x = <INT>, .y = <INT>},
        .clone_facing = <direction::>,
        .clone_type = <entity_type::>,
    });
    game_state.red_button_list.push_back(red_button{
        .button = {.x = 17, .y = 14},
        .clone_spawn = {.x = <INT>, .y = <INT>},
        .clone_facing = <direction::>,
        .clone_type = <entity_type::>,
    });
    game_state.red_button_list.push_back(red_button{
        .button = {.x = 7, .y = 17},
        .clone_spawn = {.x = <INT>, .y = <INT>},
        .clone_facing = <direction::>,
        .clone_type = <entity_type::>,
    });
    game_state.red_button_list.push_back(red_button{
        .button = {.x = 9, .y = 21},
        .clone_spawn = {.x = <INT>, .y = <INT>},
        .clone_facing = <direction::>,
        .clone_type = <entity_type::>,
    });
    game_state.red_button_list.push_back(red_button{
        .button = {.x = 7, .y = 25},
        .clone_spawn = {.x = <INT>, .y = <INT>},
        .clone_facing = <direction::>,
        .clone_type = <entity_type::>,
    });
    static_assert(decltype(game_state.red_button_list){}.capacity() >= 5);
#error "Just a friendly reminder to fill in red_button_list :)"

}

}
void load_level(state &game_state) noexcept
{
    load_level_from_rom_stub(game_state);
    load_entity_list_from_rom_stub(game_state);
}

}

