/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_60_HPP
#define CHIPPIE_LEVEL_60_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_60
{
    void load_level(state&) noexcept;
}
#endif
