/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_125_HPP
#define CHIPPIE_LEVEL_125_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_125
{
    void load_level(state&) noexcept;
}
#endif
