/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_106_HPP
#define CHIPPIE_LEVEL_106_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_106
{
    void load_level(state&) noexcept;
}
#endif
