/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_99_HPP
#define CHIPPIE_LEVEL_99_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_99
{
    void load_level(state&) noexcept;
}
#endif
