/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_23_HPP
#define CHIPPIE_LEVEL_23_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_23
{
    void load_level(state&) noexcept;
}
#endif
