/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_14_HPP
#define CHIPPIE_LEVEL_14_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_14
{
    void load_level(state&) noexcept;
}
#endif
