/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_25_HPP
#define CHIPPIE_LEVEL_25_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_25
{
    void load_level(state&) noexcept;
}
#endif
