/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_143_HPP
#define CHIPPIE_LEVEL_143_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_143
{
    void load_level(state&) noexcept;
}
#endif
