/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_110_HPP
#define CHIPPIE_LEVEL_110_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_110
{
    void load_level(state&) noexcept;
}
#endif
