/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_103_HPP
#define CHIPPIE_LEVEL_103_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_103
{
    void load_level(state&) noexcept;
}
#endif
