/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_80_HPP
#define CHIPPIE_LEVEL_80_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_80
{
    void load_level(state&) noexcept;
}
#endif
