/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_73_HPP
#define CHIPPIE_LEVEL_73_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_73
{
    void load_level(state&) noexcept;
}
#endif
