/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_92_HPP
#define CHIPPIE_LEVEL_92_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_92
{
    void load_level(state&) noexcept;
}
#endif
