/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_27_HPP
#define CHIPPIE_LEVEL_27_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_27
{
    void load_level(state&) noexcept;
}
#endif
