/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_87_HPP
#define CHIPPIE_LEVEL_87_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_87
{
    void load_level(state&) noexcept;
}
#endif
