/* AUTO GENERATED BY process_map_image.py */
#include "level.hpp"

#include <cmath>
#include <array>
#include <cstdint>

#include "level_1.hpp"
#include "level_2.hpp"
#include "level_3.hpp"
#include "level_4.hpp"
#include "level_5.hpp"
#include "level_6.hpp"
#include "level_7.hpp"
#include "level_8.hpp"
#include "level_9.hpp"
#include "level_10.hpp"
#include "level_11.hpp"
#include "level_12.hpp"
#include "level_13.hpp"
#include "level_14.hpp"
#include "level_15.hpp"
#include "level_16.hpp"
#include "level_17.hpp"
#include "level_18.hpp"
#include "level_19.hpp"
#include "level_20.hpp"
#include "level_21.hpp"
#include "level_22.hpp"
#include "level_23.hpp"
#include "level_24.hpp"
#include "level_25.hpp"
#include "level_26.hpp"
#include "level_27.hpp"
#include "level_28.hpp"
#include "level_29.hpp"
#include "level_30.hpp"
#include "level_31.hpp"
#include "level_32.hpp"
#include "level_33.hpp"
#include "level_34.hpp"
#include "level_35.hpp"
#include "level_36.hpp"
#include "level_37.hpp"
#include "level_38.hpp"
#include "level_39.hpp"
#include "level_40.hpp"
#include "level_41.hpp"
#include "level_42.hpp"
#include "level_43.hpp"
#include "level_44.hpp"
#include "level_45.hpp"
#include "level_46.hpp"
#include "level_47.hpp"
#include "level_48.hpp"
#include "level_49.hpp"
#include "level_50.hpp"
#include "level_51.hpp"
#include "level_52.hpp"
#include "level_53.hpp"
#include "level_54.hpp"
#include "level_55.hpp"
#include "level_56.hpp"
#include "level_57.hpp"
#include "level_58.hpp"
#include "level_59.hpp"
#include "level_60.hpp"
#include "level_61.hpp"
#include "level_62.hpp"
#include "level_63.hpp"
#include "level_64.hpp"
#include "level_65.hpp"
#include "level_66.hpp"
#include "level_67.hpp"
#include "level_68.hpp"
#include "level_69.hpp"
#include "level_70.hpp"
#include "level_71.hpp"
#include "level_72.hpp"
#include "level_73.hpp"
#include "level_74.hpp"
#include "level_75.hpp"
#include "level_76.hpp"
#include "level_77.hpp"
#include "level_78.hpp"
#include "level_79.hpp"
#include "level_80.hpp"
#include "level_81.hpp"
#include "level_82.hpp"
#include "level_83.hpp"
#include "level_84.hpp"
#include "level_85.hpp"
#include "level_86.hpp"
#include "level_87.hpp"
#include "level_88.hpp"
#include "level_89.hpp"
#include "level_90.hpp"
#include "level_91.hpp"
#include "level_92.hpp"
#include "level_93.hpp"
#include "level_94.hpp"
#include "level_95.hpp"
#include "level_96.hpp"
#include "level_97.hpp"
#include "level_98.hpp"
#include "level_99.hpp"
#include "level_100.hpp"
#include "level_101.hpp"
#include "level_102.hpp"
#include "level_103.hpp"
#include "level_104.hpp"
#include "level_105.hpp"
#include "level_106.hpp"
#include "level_107.hpp"
#include "level_108.hpp"
#include "level_109.hpp"
#include "level_110.hpp"
#include "level_111.hpp"
#include "level_112.hpp"
#include "level_113.hpp"
#include "level_114.hpp"
#include "level_115.hpp"
#include "level_116.hpp"
#include "level_117.hpp"
#include "level_118.hpp"
#include "level_119.hpp"
#include "level_120.hpp"
#include "level_121.hpp"
#include "level_122.hpp"
#include "level_123.hpp"
#include "level_124.hpp"
#include "level_125.hpp"
#include "level_126.hpp"
#include "level_127.hpp"
#include "level_128.hpp"
#include "level_129.hpp"
#include "level_130.hpp"
#include "level_131.hpp"
#include "level_132.hpp"
#include "level_133.hpp"
#include "level_134.hpp"
#include "level_135.hpp"
#include "level_136.hpp"
#include "level_137.hpp"
#include "level_138.hpp"
#include "level_139.hpp"
#include "level_140.hpp"
#include "level_141.hpp"
#include "level_142.hpp"
#include "level_143.hpp"
#include "level_144.hpp"
#include "level_145.hpp"
#include "level_146.hpp"
#include "level_147.hpp"
#include "level_148.hpp"
#include "level_149.hpp"

namespace chippie
{

namespace
{

constexpr std::array jump_table {
    level_1::load_level,
    level_2::load_level,
    level_3::load_level,
    level_4::load_level,
    level_5::load_level,
    level_6::load_level,
    level_7::load_level,
    level_8::load_level,
    level_9::load_level,
    level_10::load_level,
    level_11::load_level,
    level_12::load_level,
    level_13::load_level,
    level_14::load_level,
    level_15::load_level,
    level_16::load_level,
    level_17::load_level,
    level_18::load_level,
    level_19::load_level,
    level_20::load_level,
    level_21::load_level,
    level_22::load_level,
    level_23::load_level,
    level_24::load_level,
    level_25::load_level,
    level_26::load_level,
    level_27::load_level,
    level_28::load_level,
    level_29::load_level,
    level_30::load_level,
    level_31::load_level,
    level_32::load_level,
    level_33::load_level,
    level_34::load_level,
    level_35::load_level,
    level_36::load_level,
    level_37::load_level,
    level_38::load_level,
    level_39::load_level,
    level_40::load_level,
    level_41::load_level,
    level_42::load_level,
    level_43::load_level,
    level_44::load_level,
    level_45::load_level,
    level_46::load_level,
    level_47::load_level,
    level_48::load_level,
    level_49::load_level,
    level_50::load_level,
    level_51::load_level,
    level_52::load_level,
    level_53::load_level,
    level_54::load_level,
    level_55::load_level,
    level_56::load_level,
    level_57::load_level,
    level_58::load_level,
    level_59::load_level,
    level_60::load_level,
    level_61::load_level,
    level_62::load_level,
    level_63::load_level,
    level_64::load_level,
    level_65::load_level,
    level_66::load_level,
    level_67::load_level,
    level_68::load_level,
    level_69::load_level,
    level_70::load_level,
    #if 0
    level_71::load_level,
    level_72::load_level,
    level_73::load_level,
    level_74::load_level,
    level_75::load_level,
    level_76::load_level,
    level_77::load_level,
    level_78::load_level,
    level_79::load_level,
    level_80::load_level,
    level_81::load_level,
    level_82::load_level,
    level_83::load_level,
    level_84::load_level,
    level_85::load_level,
    level_86::load_level,
    level_87::load_level,
    level_88::load_level,
    level_89::load_level,
    level_90::load_level,
    level_91::load_level,
    level_92::load_level,
    level_93::load_level,
    level_94::load_level,
    level_95::load_level,
    level_96::load_level,
    level_97::load_level,
    level_98::load_level,
    level_99::load_level,
    level_100::load_level,
    level_101::load_level,
    level_102::load_level,
    level_103::load_level,
    level_104::load_level,
    level_105::load_level,
    level_106::load_level,
    level_107::load_level,
    level_108::load_level,
    level_109::load_level,
    level_110::load_level,
    level_111::load_level,
    level_112::load_level,
    level_113::load_level,
    level_114::load_level,
    level_115::load_level,
    level_116::load_level,
    level_117::load_level,
    level_118::load_level,
    level_119::load_level,
    level_120::load_level,
    level_121::load_level,
    level_122::load_level,
    level_123::load_level,
    level_124::load_level,
    level_125::load_level,
    level_126::load_level,
    level_127::load_level,
    level_128::load_level,
    level_129::load_level,
    level_130::load_level,
    level_131::load_level,
    level_132::load_level,
    level_133::load_level,
    level_134::load_level,
    level_135::load_level,
    level_136::load_level,
    level_137::load_level,
    level_138::load_level,
    level_139::load_level,
    level_140::load_level,
    level_141::load_level,
    level_142::load_level,
    level_143::load_level,
    level_144::load_level,
    level_145::load_level,
    level_146::load_level,
    level_147::load_level,
    level_148::load_level,
    level_149::load_level,
    #endif
};

}

namespace level
{
uint32_t get_max_level() noexcept
{
    return std::size(jump_table);
}

void load(state& game_state, uint32_t level) noexcept
{
    level = std::min(static_cast<uint32_t>(std::size(jump_table)), std::max(uint32_t{1U}, level));
    jump_table[level - 1](game_state);
}
}
}
