/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_107_HPP
#define CHIPPIE_LEVEL_107_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_107
{
    void load_level(state&) noexcept;
}
#endif
