/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_13_HPP
#define CHIPPIE_LEVEL_13_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_13
{
    void load_level(state&) noexcept;
}
#endif
