/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_30_HPP
#define CHIPPIE_LEVEL_30_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_30
{
    void load_level(state&) noexcept;
}
#endif
