/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_127_HPP
#define CHIPPIE_LEVEL_127_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_127
{
    void load_level(state&) noexcept;
}
#endif
