/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_141_HPP
#define CHIPPIE_LEVEL_141_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_141
{
    void load_level(state&) noexcept;
}
#endif
