/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_15_HPP
#define CHIPPIE_LEVEL_15_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_15
{
    void load_level(state&) noexcept;
}
#endif
