/* AUTO GENERATED BY process_map_image.py */
#ifndef LEVEL_HPP
#define LEVEL_HPP
#include "chippie/state/state.hpp"

namespace chippie::level
{
    [[nodiscard]] uint32_t get_max_level() noexcept;
    void load(state& game_state, uint32_t level) noexcept;
}

#endif