/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_84_HPP
#define CHIPPIE_LEVEL_84_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_84
{
    void load_level(state&) noexcept;
}
#endif
