/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_112_HPP
#define CHIPPIE_LEVEL_112_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_112
{
    void load_level(state&) noexcept;
}
#endif
