/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_34_HPP
#define CHIPPIE_LEVEL_34_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_34
{
    void load_level(state&) noexcept;
}
#endif
