/* AUTO GENERATED BY process_map_image.py */
#include "level_45.hpp"
#include "chippie/entities/entities.hpp"
#include <cstring>

namespace chippie::level_45
{
namespace
{
    constexpr int TIME_REMAINING{ 300 };
    constexpr int CHIPS_REMAINING{ 0 };
    constexpr const char* HINT_TEXT{ nullptr };
    constexpr const char* LEVEL_NAME_TEXT{ "MONSTER LAB\nPassword: OVPZ" };

    /* clang-format off */
    constexpr std::array DATA
    {
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::RED_BUTTON, terrain_type::CLEAR, terrain_type::CLONER_BLUE_TANK_THAT_MOVES_LEFT, terrain_type::WALL, terrain_type::BLUE_BUTTON, terrain_type::WALL, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::WATER, terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::RED_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::CLONER_MOVEABLE_BLOCK, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::WATER, terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::GREEN_BUTTON, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::GREEN_BUTTON_WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::FIRE_BOOTS, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, terrain_type::GREEN_BUTTON_WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, terrain_type::PUSH_FLOOR_UP, terrain_type::WALL, terrain_type::GREEN_BUTTON, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WATER, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::WATER, terrain_type::WALL, terrain_type::PUSH_FLOOR_UP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, terrain_type::PUSH_FLOOR_UP, terrain_type::WALL, terrain_type::GREEN_BUTTON, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, terrain_type::WALL, terrain_type::WATER, terrain_type::RED_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::CLONER_MOVEABLE_BLOCK, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, terrain_type::PUSH_FLOOR_UP, terrain_type::WALL, terrain_type::RED_BUTTON, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::SUCTION_BOOTS, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::WATER, terrain_type::WALL, terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, terrain_type::PUSH_FLOOR_UP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WALL, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, terrain_type::WALL, terrain_type::WATER, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::WATER, terrain_type::WALL, terrain_type::PUSH_FLOOR_UP, terrain_type::WALL, terrain_type::CLONER_PURPLE_BALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::RED_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, terrain_type::PUSH_FLOOR_UP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLONER_MOVEABLE_BLOCK, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::GREEN_BUTTON_WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, terrain_type::RED_BUTTON, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WATER, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::WATER, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, terrain_type::CLONER_CENTIPEDE, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::GREEN_BUTTON_WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WATER, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::GREEN_BUTTON_WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GREEN_BUTTON_WALL, terrain_type::CLEAR, terrain_type::RED_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLONER_MOVEABLE_BLOCK, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::GREEN_BUTTON_WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WATER, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, terrain_type::WATER, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::THIEF, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WATER, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::WATER, terrain_type::WALL, terrain_type::WATER, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, terrain_type::WATER, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GREEN_BUTTON_WALL, terrain_type::CLEAR, terrain_type::RED_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, terrain_type::WATER, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLONER_MOVEABLE_BLOCK, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, terrain_type::WATER, terrain_type::FIRE, terrain_type::FIRE, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::RED_BUTTON, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::CLONER_FIRE_DANCER, terrain_type::FIRE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::RED_BUTTON, terrain_type::RED_BUTTON, terrain_type::RED_BUTTON, terrain_type::RED_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON_CLEAR, terrain_type::RED_BUTTON, terrain_type::CLONER_CYAN_STICK_BALL, terrain_type::WALL, terrain_type::WATER, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::WATER, terrain_type::WALL, terrain_type::WATER, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PORTAL, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, terrain_type::WATER, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
    };
    /* clang-format on */

void load_level_from_rom_stub(state &game_state) noexcept
{
    /* set the time limit, if any */
    game_state.time_remaining = TIME_REMAINING;
    game_state.countdown_timer.reset();

    /* set the amount of chips for the level */
    game_state.chippie_inventory.set(inventory_item::CHIPS, CHIPS_REMAINING);

    /* set the hint string, which can be null */
    game_state.hint_text = HINT_TEXT;
    /* set the level name */
    game_state.level_name_text = LEVEL_NAME_TEXT;

    /* load the map data */
    std::memcpy(std::data(game_state.the_map.map_data), std::data(DATA), std::size(DATA) * sizeof(terrain_type));
}

void load_entity_list_from_rom_stub(state &game_state) noexcept
{
    game_state.entity_list.clear();
    uint8_t uuid = 0;

    // by convention, Chippie is always the first one in the entity_list
    game_state.entity_list.push_back(create_entity(entity_type::CHIPPIE, {.x = 3, .y = 19}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::BLUE_TANK_THAT_MOVES_LEFT, {.x = 11, .y = 2}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 30, .y = 12}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::CENTIPEDE, {.x = 8, .y = 17}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::FIRE_DANCER, {.x = 28, .y = 28}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::CYAN_STICK_BALL, {.x = 5, .y = 29}, direction::LEFT, uuid++, game_state));
    static_assert(decltype(game_state.entity_list){}.capacity() >= 6);
    game_state.red_button_list.push_back(red_button{
        .button = {.x = 10, .y = 2},
        .clone_spawn = {.x = 9, .y = 2},
        .clone_facing = direction::LEFT,
        .clone_type = entity_type::BLUE_TANK_THAT_MOVES_LEFT,
    });
    game_state.red_button_list.push_back(red_button{
        .button = {.x = 16, .y = 4},
        .clone_spawn = {.x = 18, .y = 4},
        .clone_facing = direction::UP,
        .clone_type = entity_type::MOVEABLE_BLOCK,
    });
    game_state.red_button_list.push_back(red_button{
        .button = {.x = 21, .y = 11},
        .clone_spawn = {.x = 23, .y = 11},
        .clone_facing = direction::UP,
        .clone_type = entity_type::MOVEABLE_BLOCK,
    });
    game_state.red_button_list.push_back(red_button{
        .button = {.x = 30, .y = 11},
        .clone_spawn = {.x = 30, .y = 12},
        .clone_facing = direction::UP,
        .clone_type = entity_type::PURPLE_BALL,
    });
    game_state.red_button_list.push_back(red_button{
        .button = {.x = 12, .y = 14},
        .clone_spawn = {.x = 14, .y = 14},
        .clone_facing = direction::UP,
        .clone_type = entity_type::MOVEABLE_BLOCK,
    });
    game_state.red_button_list.push_back(red_button{
        .button = {.x = 8, .y = 16},
        .clone_spawn = {.x = 8, .y = 17},
        .clone_facing = direction::UP,
        .clone_type = entity_type::CENTIPEDE,
    });
    game_state.red_button_list.push_back(red_button{
        .button = {.x = 25, .y = 21},
        .clone_spawn = {.x = 27, .y = 21},
        .clone_facing = direction::UP,
        .clone_type = entity_type::MOVEABLE_BLOCK,
    });
    game_state.red_button_list.push_back(red_button{
        .button = {.x = 11, .y = 27},
        .clone_spawn = {.x = 13, .y = 27},
        .clone_facing = direction::UP,
        .clone_type = entity_type::MOVEABLE_BLOCK,
    });
    game_state.red_button_list.push_back(red_button{
        .button = {.x = 26, .y = 28},
        .clone_spawn = {.x = 28, .y = 28},
        .clone_facing = direction::LEFT,
        .clone_type = entity_type::FIRE_DANCER,
    });
    game_state.red_button_list.push_back(red_button{
        .button = {.x = 1, .y = 29},
        .clone_spawn = {.x = 7, .y = 29},
        .clone_facing = direction::LEFT,
        .clone_type = entity_type::CYAN_STICK_BALL,
    });
    game_state.red_button_list.push_back(red_button{
        .button = {.x = 2, .y = 29},
        .clone_spawn = {.x = 7, .y = 29},
        .clone_facing = direction::LEFT,
        .clone_type = entity_type::CYAN_STICK_BALL,
    });
    game_state.red_button_list.push_back(red_button{
        .button = {.x = 3, .y = 29},
        .clone_spawn = {.x = 7, .y = 29},
        .clone_facing = direction::LEFT,
        .clone_type = entity_type::CYAN_STICK_BALL,
    });
    game_state.red_button_list.push_back(red_button{
        .button = {.x = 4, .y = 29},
        .clone_spawn = {.x = 7, .y = 29},
        .clone_facing = direction::LEFT,
        .clone_type = entity_type::CYAN_STICK_BALL,
    });
    game_state.red_button_list.push_back(red_button{
        .button = {.x = 7, .y = 29},
        .clone_spawn = {.x = 7, .y = 29},
        .clone_facing = direction::LEFT,
        .clone_type = entity_type::CYAN_STICK_BALL,
    });
    static_assert(decltype(game_state.red_button_list){}.capacity() >= 14);
}

}
void load_level(state &game_state) noexcept
{
    load_level_from_rom_stub(game_state);
    load_entity_list_from_rom_stub(game_state);
}

}

