/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_86_HPP
#define CHIPPIE_LEVEL_86_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_86
{
    void load_level(state&) noexcept;
}
#endif
