/* AUTO GENERATED BY process_map_image.py */
#include "level_121.hpp"
#include "chippie/entities/entities.hpp"
#include <cstring>

namespace chippie::level_121
{
namespace
{
    constexpr int TIME_REMAINING{ 0 };
    constexpr int CHIPS_REMAINING{ 0 };
    constexpr const char* HINT_TEXT{ nullptr };
    constexpr const char* LEVEL_NAME_TEXT{ nullptr };
#error "Just a friendly reminder to fill in time remaining, chips remaining, etc :)"

    /* clang-format off */
    constexpr std::array DATA
    {
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::RED_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLONER_FIRE_DANCER, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_DOWN, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_DOWN, terrain_type::WALL, terrain_type::WATER, terrain_type::ICE, terrain_type::WALL, terrain_type::PUSH_FLOOR_DOWN, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_DOWN, terrain_type::PUSH_FLOOR_LEFT, terrain_type::WALL, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::HINT, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::GREEN_BUTTON, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::GREEN_BUTTON, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::GREEN_BUTTON, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::PUSH_FLOOR_DOWN, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_UP, terrain_type::PUSH_FLOOR_LEFT, terrain_type::PUSH_FLOOR_UP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_LEFT, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::PUSH_FLOOR_UP, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::PUSH_FLOOR_UP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_LEFT, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::GRAVEL, terrain_type::WALL, terrain_type::RED_BUTTON, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WATER, terrain_type::CLONER_FIRE_DANCER, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::GREEN_BUTTON_CLEAR, terrain_type::WALL, terrain_type::PORTAL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::PUSH_FLOOR_DOWN, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::GRAVEL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, 
    };
    /* clang-format on */

void load_level_from_rom_stub(state &game_state) noexcept
{
    /* set the time limit, if any */
    game_state.time_remaining = TIME_REMAINING;
    game_state.countdown_timer.reset();

    /* set the amount of chips for the level */
    game_state.chippie_inventory.set(inventory_item::CHIPS, CHIPS_REMAINING);

    /* set the hint string, which can be null */
    game_state.hint_text = HINT_TEXT;
    /* set the level name */
    game_state.level_name_text = LEVEL_NAME_TEXT;

    /* load the map data */
    std::memcpy(std::data(game_state.the_map.map_data), std::data(DATA), std::size(DATA) * sizeof(terrain_type));
}

void load_entity_list_from_rom_stub(state &game_state) noexcept
{
    game_state.entity_list.clear();
    uint8_t uuid = 0;

    // by convention, Chippie is always the first one in the entity_list
    game_state.entity_list.push_back(create_entity(entity_type::CHIPPIE, {.x = 10, .y = 1}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 14, .y = 2}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 8, .y = 6}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 13, .y = 6}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::FIRE_DANCER, {.x = 4, .y = 7}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 8, .y = 7}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 13, .y = 7}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 8, .y = 8}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 13, .y = 8}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::FIRE_DANCER, {.x = 3, .y = 9}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 8, .y = 9}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 13, .y = 9}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 8, .y = 10}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 13, .y = 10}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::FIRE_DANCER, {.x = 4, .y = 11}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 8, .y = 11}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 13, .y = 11}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 8, .y = 12}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 13, .y = 12}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 8, .y = 13}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 13, .y = 13}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 8, .y = 14}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 13, .y = 14}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 8, .y = 15}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 13, .y = 15}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 8, .y = 16}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 13, .y = 16}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 5, .y = 22}, direction::LEFT, uuid++, game_state));
    static_assert(decltype(game_state.entity_list){}.capacity() >= 28);
    game_state.red_button_list.push_back(red_button{
        .button = {.x = 12, .y = 1},
        .clone_spawn = {.x = <INT>, .y = <INT>},
        .clone_facing = <direction::>,
        .clone_type = <entity_type::>,
    });
    game_state.red_button_list.push_back(red_button{
        .button = {.x = 4, .y = 22},
        .clone_spawn = {.x = <INT>, .y = <INT>},
        .clone_facing = <direction::>,
        .clone_type = <entity_type::>,
    });
    static_assert(decltype(game_state.red_button_list){}.capacity() >= 2);
#error "Just a friendly reminder to fill in red_button_list :)"
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 9, .y = 6},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 14, .y = 6},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 9, .y = 7},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 14, .y = 7},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 9, .y = 8},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 14, .y = 8},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 9, .y = 9},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 14, .y = 9},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 9, .y = 10},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 14, .y = 10},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 9, .y = 11},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 14, .y = 11},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 9, .y = 12},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 14, .y = 12},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 9, .y = 13},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 14, .y = 13},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 9, .y = 14},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 14, .y = 14},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 9, .y = 15},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 14, .y = 15},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 9, .y = 16},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 14, .y = 16},
        .trap = {.x = <INT>, .y = <INT>},
    });
    static_assert(decltype(game_state.brown_button_list){}.capacity() >= 22);
#error "Just a friendly reminder to fill in brown_button_list :)"

}

}
void load_level(state &game_state) noexcept
{
    load_level_from_rom_stub(game_state);
    load_entity_list_from_rom_stub(game_state);
}

}

