/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_142_HPP
#define CHIPPIE_LEVEL_142_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_142
{
    void load_level(state&) noexcept;
}
#endif
