#include "level_9.hpp"
#include "chippie/entities/centipede.hpp"
#include "chippie/entities/chippie_entity.hpp"
#include "chippie/entities/fire_dancer.hpp"
#include "chippie/entities/moveable_block.hpp"
#include "chippie/state/chippie_inventory.hpp"

#include <cstring>

namespace chippie::level_9
{
namespace
{
constexpr int TIME_REMAINING{400};
constexpr int CHIPS_REMAINING{9};
constexpr const char *HINT_TEXT{nullptr};
constexpr const char *LEVEL_NAME_TEXT{"NUTS AND BOLTS\nPassword: KCRE"};

/* clang-format off */
    constexpr std::array DATA
    {
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::PORTAL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::GRAVEL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GRAVEL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::GRAVEL, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::TRAP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GRAVEL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GRAVEL, terrain_type::CLEAR, terrain_type::SOCKET, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::GRAVEL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::GRAVEL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GRAVEL, terrain_type::ICE, terrain_type::ICE_TOPRIGHT, terrain_type::WALL, terrain_type::WALL, terrain_type::ICE_TOPLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_TOPRIGHT, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::GRAVEL, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::CYAN_KEY, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::ICE_BOTLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_BOTRIGHT, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE_BOTLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_TOPRIGHT, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::YELLOW_KEY, terrain_type::CYAN_DOOR, terrain_type::GREEN_BUTTON_CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GREEN_BUTTON_CLEAR, terrain_type::GREEN_DOOR, terrain_type::RED_KEY, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::GREEN_KEY, terrain_type::YELLOW_DOOR, terrain_type::GREEN_BUTTON_WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GREEN_BUTTON_WALL, terrain_type::RED_DOOR, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_BOTRIGHT, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::BOMB, terrain_type::BOMB, terrain_type::BOMB, terrain_type::BOMB, terrain_type::CLEAR, terrain_type::BOMB, terrain_type::BOMB, terrain_type::CHIP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::BOMB, terrain_type::BOMB, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::RED_KEY, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::GREEN_BUTTON, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::MAGIC_TILE_WALL, terrain_type::CHIP, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WATER, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::PUSH_FLOOR_UP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_CLEAR, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WATER, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_DOWN, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WATER, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::FIRE, terrain_type::ICE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_DOWN, terrain_type::PUSH_FLOOR_DOWN, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WATER, terrain_type::WALL, terrain_type::CLEAR, terrain_type::RED_DOOR, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::CLEAR, terrain_type::ICE, terrain_type::FIRE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::YELLOW_DOOR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_DOWN, terrain_type::PUSH_FLOOR_DOWN, terrain_type::PUSH_FLOOR_DOWN, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::FIRE, terrain_type::ICE, terrain_type::ICE, terrain_type::CLEAR, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::CLEAR, terrain_type::ICE, terrain_type::ICE, terrain_type::FIRE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_DOWN, terrain_type::PUSH_FLOOR_DOWN, terrain_type::PUSH_FLOOR_DOWN, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::FIRE, terrain_type::ICE, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::FIRE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_DOWN, terrain_type::PUSH_FLOOR_DOWN, terrain_type::PUSH_FLOOR_DOWN, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::FIRE, terrain_type::ICE, terrain_type::ICE, terrain_type::CLEAR, terrain_type::ICE, terrain_type::ICE, terrain_type::CHIP, terrain_type::ICE, terrain_type::ICE, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_DOWN, terrain_type::PUSH_FLOOR_DOWN, terrain_type::PUSH_FLOOR_DOWN, terrain_type::MAGIC_TILE_CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::FIRE, terrain_type::CLEAR, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::CLEAR, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::FIRE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::YELLOW_KEY, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::PUSH_FLOOR_UP, terrain_type::PUSH_FLOOR_LEFT, terrain_type::PUSH_FLOOR_LEFT, terrain_type::PUSH_FLOOR_LEFT, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::FIRE, terrain_type::ICE, terrain_type::CLEAR, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::CLEAR, terrain_type::ICE, terrain_type::ICE, terrain_type::FIRE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::FIRE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::CLEAR, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::CLEAR, terrain_type::ICE, terrain_type::FIRE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::FIRE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::CLEAR, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::WALL, 
    };
/* clang-format on */

void load_level_from_rom_stub(state &game_state) noexcept
{
    /* set the time limit, if any */
    game_state.time_remaining = TIME_REMAINING;
    game_state.countdown_timer.reset();

    /* set the amount of chips for the level */
    game_state.chippie_inventory.set(inventory_item::CHIPS, CHIPS_REMAINING);
    // game_state.chippie_inventory.set(inventory_item::SUCTION_BOOTS, 1);

    /* set the hint string, which can be null */
    game_state.hint_text = HINT_TEXT;
    /* set the level name */
    game_state.level_name_text = LEVEL_NAME_TEXT;

    /* load the map data */
    std::memcpy(std::data(game_state.the_map.map_data), std::data(DATA), std::size(DATA) * sizeof(terrain_type));
}

void load_entity_list_from_rom_stub(state &game_state) noexcept
{
    game_state.entity_list.clear();

    uint8_t uuid = 0;

    // by convention, Chippie is always the first one in the entity_list
    game_state.entity_list.push_back(chippie::create(game_state, {.x = 1, .y = 24}, direction::DOWN, uuid++));
    game_state.entity_list.push_back(centipede::create(game_state, {.x = 6, .y = 2}, direction::UP, uuid++));
    game_state.entity_list.push_back(centipede::create(game_state, {.x = 9, .y = 2}, direction::UP, uuid++));
    game_state.entity_list.push_back(centipede::create(game_state, {.x = 12, .y = 2}, direction::UP, uuid++));
    game_state.entity_list.push_back(centipede::create(game_state, {.x = 4, .y = 3}, direction::UP, uuid++));
    game_state.entity_list.push_back(centipede::create(game_state, {.x = 6, .y = 4}, direction::UP, uuid++));
    game_state.entity_list.push_back(centipede::create(game_state, {.x = 9, .y = 4}, direction::UP, uuid++));
    game_state.entity_list.push_back(centipede::create(game_state, {.x = 12, .y = 4}, direction::UP, uuid++));
    game_state.entity_list.push_back(fire_dancer::create(game_state, {.x = 29, .y = 4}, direction::UP, uuid++));
    game_state.entity_list.push_back(centipede::create(game_state, {.x = 13, .y = 5}, direction::UP, uuid++));
    game_state.entity_list.push_back(centipede::create(game_state, {.x = 5, .y = 6}, direction::UP, uuid++));
    game_state.entity_list.push_back(centipede::create(game_state, {.x = 8, .y = 6}, direction::UP, uuid++));
    game_state.entity_list.push_back(centipede::create(game_state, {.x = 11, .y = 6}, direction::UP, uuid++));
    game_state.entity_list.push_back(moveable_block_entity::create(game_state, {.x = 28, .y = 6}, direction::UP, uuid++));
    game_state.entity_list.push_back(fire_dancer::create(game_state, {.x = 21, .y = 11}, direction::LEFT, uuid++));
    game_state.entity_list.push_back(moveable_block_entity::create(game_state, {.x = 7, .y = 13}, direction::UP, uuid++));
    game_state.entity_list.push_back(moveable_block_entity::create(game_state, {.x = 9, .y = 13}, direction::UP, uuid++));
    game_state.entity_list.push_back(moveable_block_entity::create(game_state, {.x = 6, .y = 14}, direction::UP, uuid++));
    game_state.entity_list.push_back(moveable_block_entity::create(game_state, {.x = 8, .y = 14}, direction::UP, uuid++));
    game_state.entity_list.push_back(fire_dancer::create(game_state, {.x = 15, .y = 14}, direction::DOWN, uuid++));
    game_state.entity_list.push_back(fire_dancer::create(game_state, {.x = 27, .y = 14}, direction::UP, uuid++));
    game_state.entity_list.push_back(moveable_block_entity::create(game_state, {.x = 13, .y = 16}, direction::UP, uuid++));
    game_state.entity_list.push_back(fire_dancer::create(game_state, {.x = 21, .y = 17}, direction::RIGHT, uuid++));
    game_state.entity_list.push_back(moveable_block_entity::create(game_state, {.x = 15, .y = 25}, direction::UP, uuid++));
    game_state.entity_list.push_back(fire_dancer::create(game_state, {.x = 2, .y = 26}, direction::RIGHT, uuid++));
    game_state.entity_list.push_back(moveable_block_entity::create(game_state, {.x = 14, .y = 26}, direction::UP, uuid++));
    game_state.entity_list.push_back(moveable_block_entity::create(game_state, {.x = 13, .y = 27}, direction::UP, uuid++));
    game_state.entity_list.push_back(moveable_block_entity::create(game_state, {.x = 15, .y = 27}, direction::UP, uuid++));
    game_state.entity_list.push_back(fire_dancer::create(game_state, {.x = 4, .y = 30}, direction::LEFT, uuid++));

    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 28, .y = 5},
        .trap = {.x = 27, .y = 3},
    });
}
} // namespace

void load_level(state &game_state) noexcept
{
    load_level_from_rom_stub(game_state);
    load_entity_list_from_rom_stub(game_state);
}

} // namespace chippie::level_9
