/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_31_HPP
#define CHIPPIE_LEVEL_31_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_31
{
    void load_level(state&) noexcept;
}
#endif
