/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_108_HPP
#define CHIPPIE_LEVEL_108_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_108
{
    void load_level(state&) noexcept;
}
#endif
