/* AUTO GENERATED BY process_map_image.py */
#include "level_115.hpp"
#include "chippie/entities/entities.hpp"
#include <cstring>

namespace chippie::level_115
{
namespace
{
    constexpr int TIME_REMAINING{ 0 };
    constexpr int CHIPS_REMAINING{ 0 };
    constexpr const char* HINT_TEXT{ nullptr };
    constexpr const char* LEVEL_NAME_TEXT{ nullptr };
#error "Just a friendly reminder to fill in time remaining, chips remaining, etc :)"

    /* clang-format off */
    constexpr std::array DATA
    {
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::PORTAL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::HINT, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
    };
    /* clang-format on */

void load_level_from_rom_stub(state &game_state) noexcept
{
    /* set the time limit, if any */
    game_state.time_remaining = TIME_REMAINING;
    game_state.countdown_timer.reset();

    /* set the amount of chips for the level */
    game_state.chippie_inventory.set(inventory_item::CHIPS, CHIPS_REMAINING);

    /* set the hint string, which can be null */
    game_state.hint_text = HINT_TEXT;
    /* set the level name */
    game_state.level_name_text = LEVEL_NAME_TEXT;

    /* load the map data */
    std::memcpy(std::data(game_state.the_map.map_data), std::data(DATA), std::size(DATA) * sizeof(terrain_type));
}

void load_entity_list_from_rom_stub(state &game_state) noexcept
{
    game_state.entity_list.clear();
    uint8_t uuid = 0;

    // by convention, Chippie is always the first one in the entity_list
    game_state.entity_list.push_back(create_entity(entity_type::CHIPPIE, {.x = 11, .y = 8}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 27, .y = 25}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 25, .y = 27}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 29, .y = 27}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 27, .y = 29}, direction::UP, uuid++, game_state));
    static_assert(decltype(game_state.entity_list){}.capacity() >= 5);
    game_state.teleport_list.locations.push_back({.x = 4, .y = 4 });

    game_state.teleport_list.locations.push_back({.x = 12, .y = 4 });

    game_state.teleport_list.locations.push_back({.x = 19, .y = 4 });

    game_state.teleport_list.locations.push_back({.x = 27, .y = 4 });

    game_state.teleport_list.locations.push_back({.x = 4, .y = 12 });

    game_state.teleport_list.locations.push_back({.x = 12, .y = 12 });

    game_state.teleport_list.locations.push_back({.x = 19, .y = 12 });

    game_state.teleport_list.locations.push_back({.x = 27, .y = 12 });

    game_state.teleport_list.locations.push_back({.x = 4, .y = 19 });

    game_state.teleport_list.locations.push_back({.x = 12, .y = 19 });

    game_state.teleport_list.locations.push_back({.x = 19, .y = 19 });

    game_state.teleport_list.locations.push_back({.x = 27, .y = 19 });

    game_state.teleport_list.locations.push_back({.x = 4, .y = 27 });

    game_state.teleport_list.locations.push_back({.x = 12, .y = 27 });

    game_state.teleport_list.locations.push_back({.x = 19, .y = 27 });

    game_state.teleport_list.locations.push_back({.x = 27, .y = 27 });

    static_assert(decltype(game_state..teleport_list.locations){}.capacity() >= 16);
#error "Just a friendly reminder to order the teleport locations correctly :)"

}

}
void load_level(state &game_state) noexcept
{
    load_level_from_rom_stub(game_state);
    load_entity_list_from_rom_stub(game_state);
}

}

