/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_129_HPP
#define CHIPPIE_LEVEL_129_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_129
{
    void load_level(state&) noexcept;
}
#endif
