/* AUTO GENERATED BY process_map_image.py */
#include "level_25.hpp"
#include "chippie/entities/entities.hpp"
#include <cstring>

namespace chippie::level_25
{
namespace
{
constexpr int TIME_REMAINING{600};
constexpr int CHIPS_REMAINING{28};
constexpr const char *HINT_TEXT{nullptr};
constexpr const char *LEVEL_NAME_TEXT{"BLINK\nPassword: PQGV"};

/* clang-format off */
    constexpr std::array DATA
    {
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::PORTAL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::WALL, terrain_type::SOCKET, terrain_type::WALL, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::THIN_WALL_BOT, terrain_type::THIN_WALL_BOT, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::THIN_WALL_RIGHT, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::THIN_WALL_RIGHT, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::THIN_WALL_RIGHT, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::THIN_WALL_RIGHT, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::THIN_WALL_RIGHT, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::THIN_WALL_RIGHT, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::THIN_WALL_RIGHT, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::THIN_WALL_RIGHT, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::THIN_WALL_RIGHT, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::THIN_WALL_RIGHT, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::THIN_WALL_RIGHT, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::THIN_WALL_RIGHT, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::THIN_WALL_RIGHT, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
    };
/* clang-format on */

void load_level_from_rom_stub(state &game_state) noexcept
{
    /* set the time limit, if any */
    game_state.time_remaining = TIME_REMAINING;
    game_state.countdown_timer.reset();

    /* set the amount of chips for the level */
    game_state.chippie_inventory.set(inventory_item::CHIPS, CHIPS_REMAINING);

    /* set the hint string, which can be null */
    game_state.hint_text = HINT_TEXT;
    /* set the level name */
    game_state.level_name_text = LEVEL_NAME_TEXT;

    /* load the map data */
    std::memcpy(std::data(game_state.the_map.map_data), std::data(DATA), std::size(DATA) * sizeof(terrain_type));
}

void load_entity_list_from_rom_stub(state &game_state) noexcept
{
    game_state.entity_list.clear();
    uint8_t uuid = 0;

    // by convention, Chippie is always the first one in the entity_list
    game_state.entity_list.push_back(chippie::create(game_state, {.x = 29, .y = 21}, direction::DOWN, uuid++));

    /* teleporters */
    const Grid::Location teleporter_A{.x = 26, .y = 3};
    const Grid::Location teleporter_B{.x = 11, .y = 7};
    const Grid::Location teleporter_C{.x = 5, .y = 20};
    const Grid::Location teleporter_D{.x = 11, .y = 16};
    const Grid::Location teleporter_E{.x = 23, .y = 13};
    const Grid::Location teleporter_F{.x = 17, .y = 22};
    const Grid::Location teleporter_G{.x = 27, .y = 17};
    const Grid::Location teleporter_H{.x = 25, .y = 26};

    game_state.teleport_list.clear();

    game_state.teleport_list.push_back(teleporter{.entry_location = teleporter_A});
    game_state.teleport_list.back().set_exit(direction::DOWN, teleporter_H, direction::DOWN);
    game_state.teleport_list.back().set_exit(direction::UP, teleporter_H, direction::UP);
    game_state.teleport_list.back().set_exit(direction::LEFT, teleporter_H, direction::LEFT);
    game_state.teleport_list.back().set_exit(direction::RIGHT, teleporter_H, direction::RIGHT);

    game_state.teleport_list.push_back(teleporter{.entry_location = teleporter_B});
    game_state.teleport_list.back().set_exit(direction::DOWN, teleporter_A, direction::DOWN);
    game_state.teleport_list.back().set_exit(direction::UP, teleporter_A, direction::UP);
    game_state.teleport_list.back().set_exit(direction::LEFT, teleporter_A, direction::LEFT);
    game_state.teleport_list.back().set_exit(direction::RIGHT, teleporter_A, direction::RIGHT);

    game_state.teleport_list.push_back(teleporter{.entry_location = teleporter_C});
    game_state.teleport_list.back().set_exit(direction::DOWN, teleporter_G, direction::DOWN);
    game_state.teleport_list.back().set_exit(direction::UP, teleporter_G, direction::UP);
    game_state.teleport_list.back().set_exit(direction::LEFT, teleporter_G, direction::LEFT);
    game_state.teleport_list.back().set_exit(direction::RIGHT, teleporter_G, direction::RIGHT);

    game_state.teleport_list.push_back(teleporter{.entry_location = teleporter_D});
    game_state.teleport_list.back().set_exit(direction::DOWN, teleporter_E, direction::DOWN);
    game_state.teleport_list.back().set_exit(direction::UP, teleporter_E, direction::UP);
    game_state.teleport_list.back().set_exit(direction::LEFT, teleporter_E, direction::LEFT);
    game_state.teleport_list.back().set_exit(direction::RIGHT, teleporter_E, direction::RIGHT);

    game_state.teleport_list.push_back(teleporter{.entry_location = teleporter_E});
    game_state.teleport_list.back().set_exit(direction::DOWN, teleporter_B, direction::DOWN);
    game_state.teleport_list.back().set_exit(direction::UP, teleporter_B, direction::UP);
    game_state.teleport_list.back().set_exit(direction::LEFT, teleporter_B, direction::LEFT);
    game_state.teleport_list.back().set_exit(direction::RIGHT, teleporter_B, direction::RIGHT);

    game_state.teleport_list.push_back(teleporter{.entry_location = teleporter_F});
    game_state.teleport_list.back().set_exit(direction::DOWN, teleporter_C, direction::DOWN);
    game_state.teleport_list.back().set_exit(direction::UP, teleporter_C, direction::UP);
    game_state.teleport_list.back().set_exit(direction::LEFT, teleporter_C, direction::LEFT);
    game_state.teleport_list.back().set_exit(direction::RIGHT, teleporter_C, direction::RIGHT);

    game_state.teleport_list.push_back(teleporter{.entry_location = teleporter_G});
    game_state.teleport_list.back().set_exit(direction::UP, teleporter_D, direction::UP);
    game_state.teleport_list.back().set_exit(direction::RIGHT, teleporter_D, direction::RIGHT);
    game_state.teleport_list.back().set_exit(direction::DOWN, teleporter_D, direction::DOWN);
    game_state.teleport_list.back().set_exit(direction::LEFT, teleporter_D, direction::LEFT);

    game_state.teleport_list.push_back(teleporter{.entry_location = teleporter_H});
    game_state.teleport_list.back().set_exit(direction::DOWN, teleporter_F, direction::DOWN);
    game_state.teleport_list.back().set_exit(direction::UP, teleporter_F, direction::UP);
    game_state.teleport_list.back().set_exit(direction::LEFT, teleporter_F, direction::LEFT);
    game_state.teleport_list.back().set_exit(direction::RIGHT, teleporter_F, direction::RIGHT);

    static_assert(decltype(game_state.teleport_list){}.capacity() >= 8);
}

} // namespace
void load_level(state &game_state) noexcept
{
    load_level_from_rom_stub(game_state);
    load_entity_list_from_rom_stub(game_state);
}

} // namespace chippie::level_25
