/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_140_HPP
#define CHIPPIE_LEVEL_140_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_140
{
    void load_level(state&) noexcept;
}
#endif
