/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_19_HPP
#define CHIPPIE_LEVEL_19_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_19
{
    void load_level(state&) noexcept;
}
#endif
