/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_146_HPP
#define CHIPPIE_LEVEL_146_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_146
{
    void load_level(state&) noexcept;
}
#endif
