/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_131_HPP
#define CHIPPIE_LEVEL_131_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_131
{
    void load_level(state&) noexcept;
}
#endif
