/* AUTO GENERATED BY process_map_image.py */
#include "level_76.hpp"
#include "chippie/entities/entities.hpp"
#include <cstring>

namespace chippie::level_76
{
namespace
{
    constexpr int TIME_REMAINING{ 0 };
    constexpr int CHIPS_REMAINING{ 0 };
    constexpr const char* HINT_TEXT{ nullptr };
    constexpr const char* LEVEL_NAME_TEXT{ nullptr };
#error "Just a friendly reminder to fill in time remaining, chips remaining, etc :)"

    /* clang-format off */
    constexpr std::array DATA
    {
        terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::WALL, terrain_type::BOMB, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::CHIP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::WALL, terrain_type::PORTAL, terrain_type::ICE, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::BOMB, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::WALL, terrain_type::SOCKET, terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::BROWN_BUTTON, terrain_type::TRAP, terrain_type::GREEN_BUTTON, terrain_type::WALL, 
        terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::WALL, terrain_type::WALL, terrain_type::WATER, terrain_type::WALL, terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::WATER, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::GREEN_BUTTON, terrain_type::BROWN_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON_CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::CHIP, terrain_type::BOMB, terrain_type::CLEAR, terrain_type::GREEN_BUTTON_CLEAR, terrain_type::CLEAR, terrain_type::TRAP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::WALL, 
        terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::YELLOW_KEY, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CYAN_KEY, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::TRAP, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::CHIP, terrain_type::BOMB, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::THIN_WALL_BOTRIGHT, terrain_type::GREEN_BUTTON, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::WALL, 
        terrain_type::FIRE, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::GRAVEL, terrain_type::WALL, terrain_type::YELLOW_DOOR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::YELLOW_DOOR, terrain_type::WALL, terrain_type::GRAVEL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON_CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::FIRE, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::FIRE, terrain_type::FIRE, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::CHIP, terrain_type::BOMB, terrain_type::CLEAR, terrain_type::GREEN_BUTTON_CLEAR, terrain_type::CLEAR, terrain_type::TRAP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::FIRE, terrain_type::WALL, terrain_type::CLEAR, terrain_type::FIRE_BOOTS, terrain_type::CLEAR, terrain_type::WALL, terrain_type::RED_DOOR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CYAN_DOOR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::FLIPPERS, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::BROWN_BUTTON, terrain_type::TRAP, terrain_type::GREEN_BUTTON, terrain_type::WALL, 
        terrain_type::FIRE, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::YELLOW_KEY, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::RED_KEY, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::CHIP, terrain_type::WALL, terrain_type::PUSH_FLOOR_UP, terrain_type::WALL, terrain_type::BOMB, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::FIRE, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::CHIP, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::PUSH_FLOOR_UP, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::RED_BUTTON, terrain_type::CLONER_WATER_GLIDER, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::CHIP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::CHIP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::PUSH_FLOOR_UP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::CHIP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::ICE_TOPLEFT, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::CHIP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::CHIP, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::ICE, terrain_type::WATER, terrain_type::RED_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::ICE, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CHIP, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::ICE, terrain_type::ICE, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::CHIP, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::CLEAR, terrain_type::ICE, terrain_type::ICE, terrain_type::WALL, terrain_type::BOMB, terrain_type::WALL, 
        terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::PUSH_FLOOR_UP, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::ICE, terrain_type::ICE, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::MAGIC_TILE_WALL, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::YELLOW_DOOR, terrain_type::PUSH_FLOOR_UP, terrain_type::YELLOW_DOOR, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::ICE, terrain_type::ICE, terrain_type::WALL, terrain_type::BOMB, terrain_type::WALL, 
        terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::ICE_TOPLEFT, terrain_type::ICE_TOPRIGHT, terrain_type::ICE_TOPLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::MAGIC_TILE_CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CHIP, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::ICE, terrain_type::ICE, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_CLEAR, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_BOTLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_TOPRIGHT, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::CHIP, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::CLEAR, terrain_type::ICE, terrain_type::ICE, terrain_type::WALL, terrain_type::BOMB, terrain_type::WALL, 
        terrain_type::MAGIC_TILE_WALL, terrain_type::WALL_TRAP, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_TOPLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_BOTRIGHT, terrain_type::MAGIC_TILE_WALL, terrain_type::YELLOW_KEY, terrain_type::CLEAR, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::ICE, terrain_type::ICE, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::MAGIC_TILE_WALL, terrain_type::RED_DOOR, terrain_type::ICE_BOTLEFT, terrain_type::ICE_BOTRIGHT, terrain_type::ICE_BOTLEFT, terrain_type::CLEAR, terrain_type::ICE, terrain_type::ICE_TOPRIGHT, terrain_type::ICE_TOPLEFT, terrain_type::ICE_TOPRIGHT, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::CLEAR, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::WATER, terrain_type::CLEAR, terrain_type::ICE, terrain_type::ICE, terrain_type::WALL, terrain_type::BOMB, terrain_type::WALL, 
        terrain_type::MAGIC_TILE_WALL, terrain_type::CYAN_KEY, terrain_type::ICE_TOPLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_BOTRIGHT, terrain_type::ICE_TOPLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::RED_KEY, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::ICE, terrain_type::ICE, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::MAGIC_TILE_WALL, terrain_type::WALL_TRAP, terrain_type::ICE_BOTLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_TOPRIGHT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_BOTRIGHT, terrain_type::ICE, terrain_type::ICE_BOTLEFT, terrain_type::ICE_BOTRIGHT, terrain_type::TELEPORTER, terrain_type::CYAN_DOOR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WALL, terrain_type::CLONER_PURPLE_BALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GRAVEL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::ICE_BOTLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_BOTRIGHT, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::MAGIC_TILE_WALL, terrain_type::CLEAR, terrain_type::ICE_BOTLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::GRAVEL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GRAVEL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::MAGIC_TILE_WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
    };
    /* clang-format on */

void load_level_from_rom_stub(state &game_state) noexcept
{
    /* set the time limit, if any */
    game_state.time_remaining = TIME_REMAINING;
    game_state.countdown_timer.reset();

    /* set the amount of chips for the level */
    game_state.chippie_inventory.set(inventory_item::CHIPS, CHIPS_REMAINING);

    /* set the hint string, which can be null */
    game_state.hint_text = HINT_TEXT;
    /* set the level name */
    game_state.level_name_text = LEVEL_NAME_TEXT;

    /* load the map data */
    std::memcpy(std::data(game_state.the_map.map_data), std::data(DATA), std::size(DATA) * sizeof(terrain_type));
}

void load_entity_list_from_rom_stub(state &game_state) noexcept
{
    game_state.entity_list.clear();
    uint8_t uuid = 0;

    // by convention, Chippie is always the first one in the entity_list
    game_state.entity_list.push_back(create_entity(entity_type::CHIPPIE, {.x = 5, .y = 25}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 9, .y = 7}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 11, .y = 7}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 9, .y = 8}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 11, .y = 8}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 9, .y = 9}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 11, .y = 9}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::BACTERIA, {.x = 2, .y = 13}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::CENTIPEDE, {.x = 18, .y = 13}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 26, .y = 17}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 26, .y = 19}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 21, .y = 21}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 26, .y = 21}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 26, .y = 23}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 21, .y = 25}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 26, .y = 25}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::CENTIPEDE, {.x = 24, .y = 27}, direction::RIGHT, uuid++, game_state));
    static_assert(decltype(game_state.entity_list){}.capacity() >= 17);
    game_state.red_button_list.push_back(red_button{
        .button = {.x = 28, .y = 14},
        .clone_spawn = {.x = <INT>, .y = <INT>},
        .clone_facing = <direction::>,
        .clone_type = <entity_type::>,
    });
    game_state.red_button_list.push_back(red_button{
        .button = {.x = 19, .y = 17},
        .clone_spawn = {.x = <INT>, .y = <INT>},
        .clone_facing = <direction::>,
        .clone_type = <entity_type::>,
    });
    static_assert(decltype(game_state.red_button_list){}.capacity() >= 2);
#error "Just a friendly reminder to fill in red_button_list :)"
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 28, .y = 4},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 27, .y = 6},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 28, .y = 8},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 27, .y = 10},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 28, .y = 12},
        .trap = {.x = <INT>, .y = <INT>},
    });
    static_assert(decltype(game_state.brown_button_list){}.capacity() >= 5);
#error "Just a friendly reminder to fill in brown_button_list :)"
    game_state.teleport_list.locations.push_back({.x = 2, .y = 22 });

    game_state.teleport_list.locations.push_back({.x = 8, .y = 22 });

    game_state.teleport_list.locations.push_back({.x = 2, .y = 28 });

    game_state.teleport_list.locations.push_back({.x = 9, .y = 28 });

    static_assert(decltype(game_state..teleport_list.locations){}.capacity() >= 4);
#error "Just a friendly reminder to order the teleport locations correctly :)"

}

}
void load_level(state &game_state) noexcept
{
    load_level_from_rom_stub(game_state);
    load_entity_list_from_rom_stub(game_state);
}

}

