/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_66_HPP
#define CHIPPIE_LEVEL_66_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_66
{
    void load_level(state&) noexcept;
}
#endif
