/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_45_HPP
#define CHIPPIE_LEVEL_45_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_45
{
    void load_level(state&) noexcept;
}
#endif
