/* AUTO GENERATED BY process_map_image.py */
#include "level_118.hpp"
#include "chippie/entities/entities.hpp"
#include <cstring>

namespace chippie::level_118
{
namespace
{
    constexpr int TIME_REMAINING{ 0 };
    constexpr int CHIPS_REMAINING{ 0 };
    constexpr const char* HINT_TEXT{ nullptr };
    constexpr const char* LEVEL_NAME_TEXT{ nullptr };
#error "Just a friendly reminder to fill in time remaining, chips remaining, etc :)"

    /* clang-format off */
    constexpr std::array DATA
    {
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WATER, terrain_type::TELEPORTER, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::RED_KEY, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CYAN_DOOR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE, terrain_type::FLIPPERS, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::RED_DOOR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE_TOPRIGHT, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::PORTAL, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::GREEN_BUTTON_CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE_TOPLEFT, terrain_type::ICE, terrain_type::ICE_TOPRIGHT, terrain_type::WALL, terrain_type::WATER, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::FLIPPERS, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WATER, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::THIEF, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::TELEPORTER, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::THIEF, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::FIRE, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::FIRE_BOOTS, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::GREEN_KEY, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::BROWN_BUTTON, terrain_type::WALL, terrain_type::BLUE_BUTTON, terrain_type::CLEAR, terrain_type::WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::BROWN_BUTTON, terrain_type::CLEAR, terrain_type::FIRE, terrain_type::TELEPORTER, terrain_type::FIRE, terrain_type::ICE_BOTLEFT, terrain_type::ICE, terrain_type::ICE_BOTRIGHT, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::MAGIC_TILE_CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::TRAP, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::PUSH_FLOOR_DOWN, terrain_type::PUSH_FLOOR_LEFT, terrain_type::PUSH_FLOOR_LEFT, terrain_type::PUSH_FLOOR_LEFT, terrain_type::PUSH_FLOOR_LEFT, terrain_type::PUSH_FLOOR_LEFT, terrain_type::PUSH_FLOOR_LEFT, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::WALL_TRAP, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::PUSH_FLOOR_DOWN, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::PUSH_FLOOR_UP, terrain_type::PUSH_FLOOR_LEFT, terrain_type::PUSH_FLOOR_LEFT, terrain_type::PUSH_FLOOR_LEFT, terrain_type::MAGIC_TILE_CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::MAGIC_TILE_CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::PUSH_FLOOR_DOWN, terrain_type::ICE_TOPLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_BOTRIGHT, terrain_type::GREEN_DOOR, terrain_type::WALL, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE_TOPLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_TOPRIGHT, terrain_type::ICE, terrain_type::ICE_BOTLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_TOPRIGHT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CYAN_KEY, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE, terrain_type::ICE_TOPLEFT, terrain_type::ICE_TOPRIGHT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_TOPLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_BOTRIGHT, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE, terrain_type::ICE, terrain_type::CLEAR, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_BOTLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_TOPRIGHT, terrain_type::CLEAR, terrain_type::TELEPORTER, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE, terrain_type::ICE_BOTLEFT, terrain_type::ICE, terrain_type::ICE_BOTRIGHT, terrain_type::ICE, terrain_type::ICE_TOPLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_BOTRIGHT, terrain_type::FIRE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE_BOTLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_BOTRIGHT, terrain_type::ICE_BOTLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::CLEAR, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_BOTRIGHT, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
    };
    /* clang-format on */

void load_level_from_rom_stub(state &game_state) noexcept
{
    /* set the time limit, if any */
    game_state.time_remaining = TIME_REMAINING;
    game_state.countdown_timer.reset();

    /* set the amount of chips for the level */
    game_state.chippie_inventory.set(inventory_item::CHIPS, CHIPS_REMAINING);

    /* set the hint string, which can be null */
    game_state.hint_text = HINT_TEXT;
    /* set the level name */
    game_state.level_name_text = LEVEL_NAME_TEXT;

    /* load the map data */
    std::memcpy(std::data(game_state.the_map.map_data), std::data(DATA), std::size(DATA) * sizeof(terrain_type));
}

void load_entity_list_from_rom_stub(state &game_state) noexcept
{
    game_state.entity_list.clear();
    uint8_t uuid = 0;

    // by convention, Chippie is always the first one in the entity_list
    game_state.entity_list.push_back(create_entity(entity_type::CHIPPIE, {.x = 30, .y = 3}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::FIRE_DANCER, {.x = 4, .y = 2}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 8, .y = 6}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::CYAN_STICK_BALL, {.x = 21, .y = 6}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::WATER_GLIDER, {.x = 22, .y = 6}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::CENTIPEDE, {.x = 19, .y = 7}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::BLOB, {.x = 20, .y = 7}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::BLUE_TANK_THAT_MOVES_UP, {.x = 22, .y = 7}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::BACTERIA, {.x = 19, .y = 8}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::FIRE_DANCER, {.x = 19, .y = 9}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::BLOB, {.x = 21, .y = 9}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::BACTERIA, {.x = 22, .y = 9}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::WATER_GLIDER, {.x = 19, .y = 10}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::CYAN_STICK_BALL, {.x = 22, .y = 10}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::CYAN_STICK_BALL, {.x = 20, .y = 11}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::BLOB, {.x = 22, .y = 11}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 15, .y = 12}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::CENTIPEDE, {.x = 19, .y = 12}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::BLOB, {.x = 20, .y = 12}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::FIRE_DANCER, {.x = 21, .y = 12}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::WATER_GLIDER, {.x = 22, .y = 12}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::BLUE_TANK_THAT_MOVES_UP, {.x = 19, .y = 13}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::BLUE_TANK_THAT_MOVES_UP, {.x = 21, .y = 13}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::WATER_GLIDER, {.x = 19, .y = 14}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::BACTERIA, {.x = 20, .y = 14}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::CENTIPEDE, {.x = 22, .y = 14}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::FIRE_DANCER, {.x = 19, .y = 15}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::FIRE_DANCER, {.x = 21, .y = 15}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::BACTERIA, {.x = 22, .y = 15}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::CYAN_STICK_BALL, {.x = 20, .y = 16}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::CENTIPEDE, {.x = 19, .y = 17}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::BLUE_TANK_THAT_MOVES_UP, {.x = 20, .y = 17}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::FROG_MONSTER, {.x = 8, .y = 22}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 14, .y = 24}, direction::RIGHT, uuid++, game_state));
    static_assert(decltype(game_state.entity_list){}.capacity() >= 34);
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 17, .y = 16},
        .trap = {.x = <INT>, .y = <INT>},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 21, .y = 19},
        .trap = {.x = <INT>, .y = <INT>},
    });
    static_assert(decltype(game_state.brown_button_list){}.capacity() >= 2);
#error "Just a friendly reminder to fill in brown_button_list :)"
    game_state.teleport_list.locations.push_back({.x = 2, .y = 1 });

    game_state.teleport_list.locations.push_back({.x = 17, .y = 10 });

    game_state.teleport_list.locations.push_back({.x = 24, .y = 19 });

    game_state.teleport_list.locations.push_back({.x = 28, .y = 28 });

    static_assert(decltype(game_state..teleport_list.locations){}.capacity() >= 4);
#error "Just a friendly reminder to order the teleport locations correctly :)"

}

}
void load_level(state &game_state) noexcept
{
    load_level_from_rom_stub(game_state);
    load_entity_list_from_rom_stub(game_state);
}

}

