/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_120_HPP
#define CHIPPIE_LEVEL_120_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_120
{
    void load_level(state&) noexcept;
}
#endif
