/* AUTO GENERATED BY process_map_image.py */
#include "level_98.hpp"
#include "chippie/entities/entities.hpp"
#include <cstring>

namespace chippie::level_98
{
namespace
{
    constexpr int TIME_REMAINING{ 0 };
    constexpr int CHIPS_REMAINING{ 0 };
    constexpr const char* HINT_TEXT{ nullptr };
    constexpr const char* LEVEL_NAME_TEXT{ nullptr };
#error "Just a friendly reminder to fill in time remaining, chips remaining, etc :)"

    /* clang-format off */
    constexpr std::array DATA
    {
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE_TOPLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_TOPRIGHT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE, terrain_type::PUSH_FLOOR_LEFT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE_TOPLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_TOPRIGHT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE_TOPLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_TOPRIGHT, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::ICE, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE, terrain_type::PUSH_FLOOR_LEFT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::ICE, terrain_type::WALL, terrain_type::SOCKET, terrain_type::WALL, terrain_type::ICE, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::SOCKET, terrain_type::PORTAL, terrain_type::SOCKET, terrain_type::ICE, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE, terrain_type::PUSH_FLOOR_LEFT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::ICE, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE, terrain_type::PUSH_FLOOR_LEFT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::ICE, terrain_type::WALL, terrain_type::SOCKET, terrain_type::WALL, terrain_type::ICE, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE_BOTLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_BOTRIGHT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE_BOTLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_BOTRIGHT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE_BOTLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_BOTRIGHT, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_UP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_UP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_UP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_UP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_UP, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_UP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_DOWN, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_DOWN, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE_TOPLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_TOPRIGHT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_DOWN, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_DOWN, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE_TOPLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_TOPRIGHT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE_TOPLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_TOPRIGHT, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::PUSH_FLOOR_LEFT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE, terrain_type::PUSH_FLOOR_LEFT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::ICE, terrain_type::PUSH_FLOOR_LEFT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::PUSH_FLOOR_LEFT, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE_BOTLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_BOTRIGHT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_UP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_UP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE_BOTLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_BOTRIGHT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE_BOTLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_BOTRIGHT, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_UP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_UP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_UP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_UP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_DOWN, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_DOWN, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_DOWN, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_DOWN, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_DOWN, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_DOWN, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE_TOPLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_TOPRIGHT, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE_TOPLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_TOPRIGHT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE_TOPLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_TOPRIGHT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::ICE, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::ICE, terrain_type::PUSH_FLOOR_LEFT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::ICE, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::ICE, terrain_type::PUSH_FLOOR_LEFT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::ICE, terrain_type::PUSH_FLOOR_LEFT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::ICE, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::ICE, terrain_type::PUSH_FLOOR_LEFT, terrain_type::CLEAR, terrain_type::PUSH_FLOOR_RIGHT, terrain_type::ICE, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::ICE_BOTLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_BOTRIGHT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE_BOTLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_BOTRIGHT, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::ICE_BOTLEFT, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE, terrain_type::ICE_BOTRIGHT, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
    };
    /* clang-format on */

void load_level_from_rom_stub(state &game_state) noexcept
{
    /* set the time limit, if any */
    game_state.time_remaining = TIME_REMAINING;
    game_state.countdown_timer.reset();

    /* set the amount of chips for the level */
    game_state.chippie_inventory.set(inventory_item::CHIPS, CHIPS_REMAINING);

    /* set the hint string, which can be null */
    game_state.hint_text = HINT_TEXT;
    /* set the level name */
    game_state.level_name_text = LEVEL_NAME_TEXT;

    /* load the map data */
    std::memcpy(std::data(game_state.the_map.map_data), std::data(DATA), std::size(DATA) * sizeof(terrain_type));
}

void load_entity_list_from_rom_stub(state &game_state) noexcept
{
    game_state.entity_list.clear();
    uint8_t uuid = 0;

    // by convention, Chippie is always the first one in the entity_list
    game_state.entity_list.push_back(create_entity(entity_type::CHIPPIE, {.x = 14, .y = 15}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 3, .y = 1}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 5, .y = 1}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 1, .y = 2}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 6, .y = 2}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 15, .y = 2}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 17, .y = 2}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 27, .y = 2}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 28, .y = 2}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 13, .y = 3}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 18, .y = 3}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 29, .y = 3}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 25, .y = 4}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 1, .y = 5}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 6, .y = 5}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 13, .y = 5}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 18, .y = 5}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 25, .y = 5}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 29, .y = 5}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 2, .y = 6}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 4, .y = 6}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 9, .y = 6}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 10, .y = 6}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 14, .y = 6}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 16, .y = 6}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 26, .y = 6}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 28, .y = 6}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 9, .y = 7}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 21, .y = 7}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 22, .y = 7}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 22, .y = 8}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 24, .y = 8}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 25, .y = 8}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 5, .y = 9}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 6, .y = 9}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 8, .y = 9}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 9, .y = 9}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 19, .y = 9}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 20, .y = 9}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 25, .y = 9}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 5, .y = 10}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 8, .y = 10}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 20, .y = 10}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 14, .y = 11}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 2, .y = 12}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 4, .y = 12}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 24, .y = 12}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 26, .y = 12}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 1, .y = 14}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 6, .y = 14}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 10, .y = 14}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 18, .y = 14}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 22, .y = 15}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 30, .y = 15}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 1, .y = 16}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 6, .y = 16}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 30, .y = 17}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 2, .y = 18}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 5, .y = 18}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 22, .y = 18}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 16, .y = 19}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 25, .y = 19}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 27, .y = 19}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 5, .y = 20}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 8, .y = 20}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 20, .y = 20}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 5, .y = 21}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 6, .y = 21}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 8, .y = 21}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 9, .y = 21}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 19, .y = 21}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 20, .y = 21}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 9, .y = 23}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 21, .y = 23}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 25, .y = 23}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 27, .y = 23}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 3, .y = 24}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 6, .y = 24}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 9, .y = 24}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 10, .y = 24}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 13, .y = 24}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 16, .y = 24}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 20, .y = 24}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::MOVEABLE_BLOCK, {.x = 21, .y = 24}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 7, .y = 25}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 19, .y = 25}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 23, .y = 25}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 30, .y = 25}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 1, .y = 26}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 12, .y = 26}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 7, .y = 27}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 19, .y = 27}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 30, .y = 27}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 12, .y = 28}, direction::UP, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 23, .y = 28}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 1, .y = 29}, direction::DOWN, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 2, .y = 30}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 4, .y = 30}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 14, .y = 30}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 16, .y = 30}, direction::LEFT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 25, .y = 30}, direction::RIGHT, uuid++, game_state));
    game_state.entity_list.push_back(create_entity(entity_type::PURPLE_BALL, {.x = 27, .y = 30}, direction::RIGHT, uuid++, game_state));
    static_assert(decltype(game_state.entity_list){}.capacity() >= 102);

}

}
void load_level(state &game_state) noexcept
{
    load_level_from_rom_stub(game_state);
    load_entity_list_from_rom_stub(game_state);
}

}

