/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_113_HPP
#define CHIPPIE_LEVEL_113_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_113
{
    void load_level(state&) noexcept;
}
#endif
