/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_136_HPP
#define CHIPPIE_LEVEL_136_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_136
{
    void load_level(state&) noexcept;
}
#endif
