/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_37_HPP
#define CHIPPIE_LEVEL_37_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_37
{
    void load_level(state&) noexcept;
}
#endif
