/* AUTO GENERATED BY process_map_image.py */
#include "level_36.hpp"
#include "chippie/entities/entities.hpp"
#include <cstring>

namespace chippie::level_36
{
namespace
{
    constexpr int TIME_REMAINING{ 350 };
    constexpr int CHIPS_REMAINING{ 28 };
    constexpr const char* HINT_TEXT{ nullptr };
    constexpr const char* LEVEL_NAME_TEXT{ "LADDER\nPassword: NXIS" };

    /* clang-format off */
    constexpr std::array DATA
    {
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::GREEN_BUTTON_WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CYAN_DOOR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::RED_KEY, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::CYAN_KEY, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::BROWN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::BROWN_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON_CLEAR, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::BROWN_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON_WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::BROWN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::BROWN_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON_CLEAR, terrain_type::TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::BROWN_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON_WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::BROWN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::BROWN_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON_CLEAR, terrain_type::TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::GREEN_BUTTON_WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::BROWN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::TRAP, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::BROWN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::BROWN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::TRAP, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::GREEN_BUTTON, terrain_type::GREEN_BUTTON_CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::BROWN_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON_CLEAR, terrain_type::TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL_TRAP, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::BLUE_BUTTON, terrain_type::WALL, terrain_type::BROWN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::BROWN_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON_WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::GREEN_BUTTON, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CYAN_DOOR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::BROWN_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON_CLEAR, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::BROWN_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON_WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::BROWN_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON_CLEAR, terrain_type::TRAP, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::CHIP, terrain_type::WALL_TRAP, terrain_type::CHIP, terrain_type::WALL_TRAP, terrain_type::CHIP, terrain_type::WALL_TRAP, terrain_type::CHIP, terrain_type::WALL_TRAP, terrain_type::CYAN_KEY, terrain_type::WALL_TRAP, terrain_type::CHIP, terrain_type::WALL_TRAP, terrain_type::CHIP, terrain_type::WALL_TRAP, terrain_type::CHIP, terrain_type::WALL_TRAP, terrain_type::CHIP, terrain_type::WALL_TRAP, terrain_type::CHIP, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::BROWN_BUTTON, terrain_type::CLEAR, terrain_type::GREEN_BUTTON_WALL, terrain_type::TRAP, terrain_type::WALL, terrain_type::THIN_WALL_BOT, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::PORTAL, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::GREEN_BUTTON_CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::SOCKET, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::WALL, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::CHIP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, terrain_type::WALL, terrain_type::CLEAR, terrain_type::RED_DOOR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::WALL_TRAP, terrain_type::CLEAR, terrain_type::CLEAR, terrain_type::WALL, 
        terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, terrain_type::WALL, 
    };
    /* clang-format on */

void load_level_from_rom_stub(state &game_state) noexcept
{
    /* set the time limit, if any */
    game_state.time_remaining = TIME_REMAINING;
    game_state.countdown_timer.reset();

    /* set the amount of chips for the level */
    game_state.chippie_inventory.set(inventory_item::CHIPS, CHIPS_REMAINING);

    /* set the hint string, which can be null */
    game_state.hint_text = HINT_TEXT;
    /* set the level name */
    game_state.level_name_text = LEVEL_NAME_TEXT;

    /* load the map data */
    std::memcpy(std::data(game_state.the_map.map_data), std::data(DATA), std::size(DATA) * sizeof(terrain_type));
}

void load_entity_list_from_rom_stub(state &game_state) noexcept
{
    game_state.entity_list.clear();
    uint8_t uuid = 0;

    // by convention, Chippie is always the first one in the entity_list
    game_state.entity_list.push_back(chippie::create(game_state, {.x = 29, .y = 1}, direction::DOWN, uuid++));
    game_state.entity_list.push_back(blue_tank::create(game_state, {.x = 13, .y = 2}, direction::LEFT, uuid++));
    game_state.entity_list.push_back(moveable_block_entity::create(game_state, {.x = 2, .y = 3}, direction::UP, uuid++));
    game_state.entity_list.push_back(moveable_block_entity::create(game_state, {.x = 2, .y = 5}, direction::UP, uuid++));
    game_state.entity_list.push_back(blue_tank::create(game_state, {.x = 13, .y = 6}, direction::LEFT, uuid++));
    game_state.entity_list.push_back(moveable_block_entity::create(game_state, {.x = 2, .y = 7}, direction::UP, uuid++));
    game_state.entity_list.push_back(moveable_block_entity::create(game_state, {.x = 2, .y = 9}, direction::UP, uuid++));
    game_state.entity_list.push_back(blue_tank::create(game_state, {.x = 13, .y = 10}, direction::LEFT, uuid++));
    game_state.entity_list.push_back(moveable_block_entity::create(game_state, {.x = 2, .y = 11}, direction::UP, uuid++));
    game_state.entity_list.push_back(moveable_block_entity::create(game_state, {.x = 2, .y = 13}, direction::UP, uuid++));
    game_state.entity_list.push_back(blue_tank::create(game_state, {.x = 13, .y = 14}, direction::LEFT, uuid++));
    game_state.entity_list.push_back(moveable_block_entity::create(game_state, {.x = 2, .y = 15}, direction::UP, uuid++));
    game_state.entity_list.push_back(moveable_block_entity::create(game_state, {.x = 2, .y = 17}, direction::UP, uuid++));
    game_state.entity_list.push_back(blue_tank::create(game_state, {.x = 13, .y = 18}, direction::LEFT, uuid++));
    game_state.entity_list.push_back(moveable_block_entity::create(game_state, {.x = 2, .y = 19}, direction::UP, uuid++));
    game_state.entity_list.push_back(moveable_block_entity::create(game_state, {.x = 2, .y = 21}, direction::UP, uuid++));
    game_state.entity_list.push_back(moveable_block_entity::create(game_state, {.x = 2, .y = 23}, direction::UP, uuid++));
    game_state.entity_list.push_back(moveable_block_entity::create(game_state, {.x = 2, .y = 25}, direction::UP, uuid++));
    game_state.entity_list.push_back(moveable_block_entity::create(game_state, {.x = 2, .y = 27}, direction::UP, uuid++));
    static_assert(decltype(game_state.entity_list){}.capacity() >= 19);
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 6, .y = 2},
        .trap = {.x = 13, .y = 2},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 1, .y = 3},
        .trap = {.x = 4, .y = 3},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 1, .y = 5},
        .trap = {.x = 4, .y = 5},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 7, .y = 6},
        .trap = {.x = 13, .y = 6},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 1, .y = 7},
        .trap = {.x = 4, .y = 7},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 1, .y = 9},
        .trap = {.x = 4, .y = 9},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 8, .y = 10},
        .trap = {.x = 13, .y = 10},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 1, .y = 11},
        .trap = {.x = 4, .y = 11},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 1, .y = 13},
        .trap = {.x = 4, .y = 13},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 9, .y = 14},
        .trap = {.x = 13, .y = 14},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 1, .y = 15},
        .trap = {.x = 4, .y = 15},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 1, .y = 17},
        .trap = {.x = 4, .y = 17},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 10, .y = 18},
        .trap = {.x = 13, .y = 18},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 1, .y = 19},
        .trap = {.x = 4, .y = 19},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 1, .y = 21},
        .trap = {.x = 4, .y = 21},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 1, .y = 23},
        .trap = {.x = 4, .y = 23},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 1, .y = 25},
        .trap = {.x = 4, .y = 25},
    });
    game_state.brown_button_list.push_back(brown_button{
        .button = {.x = 1, .y = 27},
        .trap = {.x = 4, .y = 27},
    });
    static_assert(decltype(game_state.brown_button_list){}.capacity() >= 18);

}

}
void load_level(state &game_state) noexcept
{
    load_level_from_rom_stub(game_state);
    load_entity_list_from_rom_stub(game_state);
}

}

