/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_12_HPP
#define CHIPPIE_LEVEL_12_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_12
{
    void load_level(state&) noexcept;
}
#endif
