/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_135_HPP
#define CHIPPIE_LEVEL_135_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_135
{
    void load_level(state&) noexcept;
}
#endif
