/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_118_HPP
#define CHIPPIE_LEVEL_118_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_118
{
    void load_level(state&) noexcept;
}
#endif
