/* AUTO GENERATED BY process_map_image.py */
#ifndef CHIPPIE_LEVEL_18_HPP
#define CHIPPIE_LEVEL_18_HPP

#include "chippie/state/state.hpp"

namespace chippie::level_18
{
    void load_level(state&) noexcept;
}
#endif
