#ifndef BLOB_HPP
#define BLOB_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::blob {

namespace {

inline constexpr std::array tile_data { embp::pfold(
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,GREEN,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,GREEN,GREEN,GREEN,LCYAN,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,GREEN,GREEN,DRKGRY,GREEN,GREEN,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,DRKGRY,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,GREEN,GREEN,DRKGRY,GREEN,GREEN,GREEN,DRKGRY,GREEN,GREEN,LCYAN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LCYAN,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,GREEN,GREEN,LCYAN,GREEN,DRKGRY,GREEN,GREEN,LCYAN,GREEN,DRKGRY,GREEN,GREEN,DRKGRY,GREEN,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LCYAN,GREEN,GREEN,GREEN,DRKGRY,GREEN,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,GREEN,DRKGRY,GREEN,GREEN,LCYAN,GREEN,DRKGRY,GREEN,LCYAN,GREEN,GREEN,GREEN,GREEN,LCYAN,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,DRKGRY,GREEN,GREEN,GREEN,GREEN,LCYAN,GREEN,GREEN,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,GREEN,LCYAN,GREEN,DRKGRY,GREEN,LCYAN,GREEN,DRKGRY,GREEN,GREEN,GREEN,GREEN,DRKGRY,GREEN,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LCYAN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,DRKGRY,GREEN,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,GREEN,GREEN,GREEN,GREEN,DRKGRY,GREEN,GREEN,GREEN,GREEN,GREEN,LGREY,GREEN,LCYAN,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,LGREY,LGREY,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 1,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::blob
#endif
