#ifndef BLUE_TANK_LEFT_HPP
#define BLUE_TANK_LEFT_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::blue_tank_left {

namespace {

inline constexpr std::array tile_data { embp::pfold(
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,BLACK,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLACK,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLUE,BLUE,BLACK,BLACK,BLACK,BLUE,BLACK,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLACK,BLACK,DRKGRY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLUE,BLUE,BLUE,BLUE,BLACK,BLACK,BLACK,BLACK,BLUE,BLUE,BLUE,BLACK,DRKGRY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLUE,BLUE,BLUE,BLACK,BLUE,BLUE,BLACK,BLACK,BLACK,BLUE,BLUE,BLACK,DRKGRY,LGREY,
LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLUE,BLUE,BLUE,BLUE,BLACK,BLACK,BLACK,BLUE,BLACK,DRKGRY,LGREY,
LGREY,LGREY,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLUE,BLUE,BLUE,BLUE,BLACK,BLACK,BLACK,BLUE,BLACK,DRKGRY,LGREY,
LGREY,LGREY,BLACK,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,BLUE,BLUE,BLUE,BLUE,BLUE,BLACK,BLACK,BLUE,BLACK,DRKGRY,LGREY,
LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLUE,BLUE,BLUE,BLUE,BLUE,BLACK,BLACK,BLUE,BLACK,DRKGRY,LGREY,
LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,BLUE,BLUE,BLUE,BLACK,BLUE,BLUE,BLUE,BLACK,BLACK,BLUE,BLUE,BLACK,DRKGRY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLUE,BLUE,BLUE,BLUE,BLACK,BLACK,BLACK,BLACK,BLUE,BLUE,BLUE,BLACK,DRKGRY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLACK,BLACK,DRKGRY,DRKGRY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,BLACK,BLUE,BLUE,BLACK,BLUE,BLACK,BLUE,BLACK,DRKGRY,DRKGRY,DRKGRY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLUE,BLUE,BLACK,BLUE,BLUE,BLUE,BLACK,DRKGRY,DRKGRY,DRKGRY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,DRKGRY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,BLACK,DRKGRY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,DRKGRY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 1,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::blue_tank_left
#endif
