#ifndef BOMB_HPP
#define BOMB_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::bomb {

namespace {

inline constexpr std::array tile_data { embp::pfold(
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,LGREY,LGREY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,DRKGRY,LGREY,LGREY,LGREY,LGREY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,DRKGRY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,DRKGRY,LGREY,LGREY,LGREY,BLACK,RED,RED,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LYELLOW,LGREY,RED,LGREY,LGREY,BLACK,RED,DRKGRY,BLACK,RED,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,RED,LGREY,RED,LYELLOW,LGREY,LGREY,BLACK,DRKGRY,RED,BLACK,RED,RED,RED,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LYELLOW,LGREY,RED,LGREY,BLACK,RED,BLACK,BLACK,RED,RED,RED,RED,RED,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,RED,LYELLOW,LGREY,RED,LGREY,LGREY,BLACK,RED,RED,RED,RED,RED,RED,RED,RED,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,RED,LGREY,LGREY,LGREY,BLACK,RED,RED,RED,RED,RED,RED,RED,RED,RED,DRKGRY,BLACK,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,RED,RED,RED,RED,RED,RED,RED,RED,DRKGRY,RED,BLACK,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,RED,RED,RED,RED,RED,RED,DRKGRY,RED,BLACK,DRKGRY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,RED,RED,RED,DRKGRY,RED,DRKGRY,RED,DRKGRY,BLACK,DRKGRY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,RED,DRKGRY,RED,DRKGRY,RED,DRKGRY,BLACK,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,DRKGRY,RED,BLACK,BLACK,DRKGRY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,BLACK,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::bomb
#endif
