#ifndef CAMPFIRE_HPP
#define CAMPFIRE_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::campfire {

namespace {

inline constexpr std::array tile_data { embp::pfold(
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LYELLOW,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LYELLOW,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LYELLOW,YELLOW,LYELLOW,LGREY,LGREY,LYELLOW,YELLOW,LYELLOW,YELLOW,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,YELLOW,RED,YELLOW,LGREY,LGREY,YELLOW,RED,RED,LYELLOW,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LYELLOW,RED,LYELLOW,LGREY,LGREY,LGREY,YELLOW,RED,YELLOW,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,YELLOW,RED,YELLOW,LYELLOW,YELLOW,LGREY,LYELLOW,RED,LYELLOW,YELLOW,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LYELLOW,YELLOW,YELLOW,YELLOW,LYELLOW,LGREY,YELLOW,RED,RED,LYELLOW,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,YELLOW,RED,RED,LYELLOW,YELLOW,LYELLOW,YELLOW,RED,RED,YELLOW,LYELLOW,YELLOW,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,YELLOW,LYELLOW,RED,RED,RED,YELLOW,RED,YELLOW,LYELLOW,RED,RED,YELLOW,RED,LYELLOW,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LYELLOW,RED,RED,RED,LYELLOW,YELLOW,YELLOW,LYELLOW,RED,RED,RED,YELLOW,RED,YELLOW,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,YELLOW,LYELLOW,RED,RED,YELLOW,RED,LYELLOW,YELLOW,YELLOW,LYELLOW,RED,RED,RED,LYELLOW,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,YELLOW,YELLOW,RED,LYELLOW,RED,RED,RED,RED,YELLOW,RED,RED,RED,YELLOW,DRKGRY,DRKGRY,DRKGRY,LGREY,DRKGRY,
WHITE,LGREY,DRKGRY,DRKGRY,DRKGRY,BROWN,BROWN,YELLOW,YELLOW,YELLOW,YELLOW,RED,RED,RED,YELLOW,RED,RED,YELLOW,YELLOW,BROWN,BROWN,DRKGRY,LGREY,DRKGRY,
WHITE,LGREY,DRKGRY,BROWN,BROWN,BROWN,BROWN,BROWN,YELLOW,BROWN,YELLOW,YELLOW,RED,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BROWN,BROWN,DRKGRY,DRKGRY,LGREY,DRKGRY,
WHITE,DRKGRY,DRKGRY,BROWN,BROWN,BROWN,DRKGRY,DRKGRY,DRKGRY,BROWN,BROWN,YELLOW,YELLOW,YELLOW,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BROWN,BROWN,DRKGRY,LGREY,LGREY,DRKGRY,
WHITE,DRKGRY,DRKGRY,BROWN,BROWN,DRKGRY,DRKGRY,BROWN,BROWN,BROWN,BROWN,DRKGRY,DRKGRY,BROWN,BROWN,BROWN,BROWN,DRKGRY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BROWN,BROWN,BROWN,DRKGRY,DRKGRY,LGREY,LGREY,DRKGRY,DRKGRY,BROWN,BROWN,BROWN,BROWN,DRKGRY,DRKGRY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,DRKGRY,BROWN,BROWN,BROWN,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,BROWN,BROWN,BROWN,DRKGRY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,BROWN,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::campfire
#endif
