#ifndef CENTIPEDE_DOWN_HPP
#define CENTIPEDE_DOWN_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::centipede_down {

namespace {

inline constexpr std::array tile_data { embp::pfold(
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,YELLOW,YELLOW,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,RED,DRKGRY,LGREY,LGREY,BLACK,BLACK,YELLOW,LYELLOW,LYELLOW,LYELLOW,BLACK,BLACK,LGREY,LGREY,LGREY,DRKGRY,RED,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,RED,DRKGRY,LGREY,BLACK,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,LGREY,LGREY,DRKGRY,RED,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,RED,DRKGRY,BLACK,YELLOW,YELLOW,LYELLOW,LYELLOW,LYELLOW,LYELLOW,LYELLOW,LYELLOW,LYELLOW,LYELLOW,BLACK,DRKGRY,RED,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,RED,BLACK,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LYELLOW,BLACK,RED,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,BLACK,YELLOW,YELLOW,LYELLOW,LYELLOW,LYELLOW,LYELLOW,LYELLOW,LYELLOW,BLACK,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,RED,DRKGRY,DRKGRY,BLACK,YELLOW,BLACK,BLACK,BLACK,BLACK,LYELLOW,BLACK,DRKGRY,DRKGRY,RED,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,RED,RED,RED,BLACK,YELLOW,YELLOW,LYELLOW,LYELLOW,BLACK,RED,RED,RED,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,YELLOW,LYELLOW,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,RED,RED,RED,BLACK,YELLOW,YELLOW,BLACK,RED,RED,RED,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,RED,LGREY,LGREY,BLACK,YELLOW,YELLOW,LYELLOW,LYELLOW,BLACK,LGREY,LGREY,RED,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,RED,LGREY,LGREY,BLACK,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LYELLOW,BLACK,LGREY,LGREY,RED,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,RED,LGREY,LGREY,BLACK,YELLOW,LYELLOW,LYELLOW,LYELLOW,LYELLOW,LYELLOW,BLACK,LGREY,LGREY,RED,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,YELLOW,YELLOW,YELLOW,LYELLOW,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LYELLOW,LYELLOW,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,LGREY,LGREY,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LGREY,LGREY,LGREY,LGREY,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 1,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::centipede_down
#endif
