#ifndef CENTIPEDE_LEFT_HPP
#define CENTIPEDE_LEFT_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::centipede_left {

namespace {

inline constexpr std::array tile_data { embp::pfold(
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,RED,RED,RED,DRKGRY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,RED,RED,DRKGRY,LGREY,LGREY,LGREY,LGREY,RED,DRKGRY,RED,DRKGRY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,RED,DRKGRY,LGREY,LGREY,RED,DRKGRY,DRKGRY,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,RED,DRKGRY,LGREY,RED,DRKGRY,BLACK,YELLOW,YELLOW,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,LGREY,RED,DRKGRY,LGREY,RED,BLACK,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,BLACK,BLACK,LGREY,LGREY,BLACK,YELLOW,YELLOW,BLACK,RED,DRKGRY,LGREY,BLACK,YELLOW,YELLOW,YELLOW,LYELLOW,YELLOW,BLACK,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,BLACK,LGREY,BLACK,YELLOW,LYELLOW,YELLOW,YELLOW,BLACK,DRKGRY,BLACK,YELLOW,BLACK,LYELLOW,YELLOW,LYELLOW,YELLOW,YELLOW,BLACK,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,BLACK,LYELLOW,YELLOW,LYELLOW,YELLOW,YELLOW,YELLOW,BLACK,YELLOW,YELLOW,BLACK,LYELLOW,YELLOW,LYELLOW,YELLOW,LYELLOW,YELLOW,BLACK,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,BLACK,LYELLOW,YELLOW,LYELLOW,YELLOW,LYELLOW,YELLOW,BLACK,LYELLOW,LYELLOW,BLACK,LYELLOW,YELLOW,LYELLOW,YELLOW,LYELLOW,YELLOW,BLACK,LGREY,LGREY,
LGREY,LGREY,LGREY,BLACK,LGREY,BLACK,LYELLOW,LYELLOW,YELLOW,LYELLOW,BLACK,DRKGRY,BLACK,LYELLOW,BLACK,LYELLOW,YELLOW,LYELLOW,YELLOW,LYELLOW,BLACK,LGREY,LGREY,LGREY,
LGREY,LGREY,BLACK,BLACK,LGREY,LGREY,BLACK,LYELLOW,LYELLOW,BLACK,RED,DRKGRY,LGREY,BLACK,LYELLOW,LYELLOW,YELLOW,LYELLOW,YELLOW,BLACK,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,LGREY,RED,DRKGRY,LGREY,RED,BLACK,LYELLOW,YELLOW,LYELLOW,YELLOW,BLACK,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,RED,DRKGRY,LGREY,RED,DRKGRY,BLACK,LYELLOW,LYELLOW,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,RED,DRKGRY,LGREY,LGREY,RED,DRKGRY,DRKGRY,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,RED,RED,DRKGRY,LGREY,LGREY,LGREY,LGREY,RED,DRKGRY,RED,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,RED,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,RED,RED,DRKGRY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 1,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::centipede_left
#endif
