#ifndef CHIPPIE_DOWN_GIRL_HPP
#define CHIPPIE_DOWN_GIRL_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::chippie_down_girl {

namespace {

inline constexpr std::array tile_data { embp::pfold(
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,YELLOW,YELLOW,YELLOW,YELLOW,LYELLOW,LYELLOW,YELLOW,YELLOW,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,YELLOW,YELLOW,LYELLOW,LYELLOW,LYELLOW,LYELLOW,LYELLOW,YELLOW,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,YELLOW,LYELLOW,BLACK,LYELLOW,LYELLOW,BLACK,LYELLOW,YELLOW,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,YELLOW,LYELLOW,LYELLOW,BLACK,BLACK,LYELLOW,LYELLOW,YELLOW,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,YELLOW,YELLOW,BLACK,LYELLOW,LYELLOW,LYELLOW,LYELLOW,BLACK,YELLOW,YELLOW,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,YELLOW,YELLOW,LGREY,BLACK,BLACK,BLACK,BLACK,LGREY,YELLOW,YELLOW,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,BLACK,LYELLOW,BLACK,LGREY,BLACK,CYAN,LCYAN,CYAN,LCYAN,CYAN,CYAN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,BLACK,LYELLOW,BLACK,BLACK,CYAN,BLACK,CYAN,CYAN,CYAN,CYAN,BLACK,CYAN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,CYAN,BLACK,BLACK,BLACK,LCYAN,CYAN,CYAN,CYAN,DRKGRY,BLACK,CYAN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,CYAN,BLACK,LGREY,BLACK,CYAN,CYAN,CYAN,CYAN,BLACK,LGREY,BLACK,CYAN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LGREY,LGREY,BLACK,LCYAN,CYAN,CYAN,CYAN,DRKGRY,LGREY,LGREY,BLACK,LYELLOW,BLACK,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,CYAN,CYAN,CYAN,CYAN,BLACK,LGREY,LGREY,LGREY,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LGREEN,GREEN,GREEN,GREEN,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,GREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,GREEN,GREEN,LGREEN,GREEN,LGREEN,GREEN,LGREEN,GREEN,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,GREEN,LGREEN,GREEN,LGREEN,GREEN,LGREEN,GREEN,GREEN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,DRKGRY,DRKGRY,BLACK,BLACK,BLACK,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LBLUE,DRKGRY,DRKGRY,LBLUE,BLACK,DRKGRY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LBLUE,LBLUE,DRKGRY,DRKGRY,LBLUE,LBLUE,DRKGRY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 1,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::chippie_down_girl
#endif
