#ifndef CHIP_HPP
#define CHIP_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::chip {

namespace {

inline constexpr std::array tile_data { embp::pfold(
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,DRKGRY,BLACK,LGREY,LGREY,BLACK,DRKGRY,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LGREY,LGREY,LGREY,BLACK,BLACK,LGREY,LGREY,LGREY,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,LGREY,LGREY,DRKGRY,LGREY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,BLACK,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,BLACK,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,BLACK,DRKGRY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,DRKGRY,DRKGRY,BLACK,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,BLACK,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,BLACK,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,BLACK,DRKGRY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,DRKGRY,DRKGRY,BLACK,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,BLACK,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,BLACK,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,BLACK,DRKGRY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,DRKGRY,DRKGRY,BLACK,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,BLACK,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,BLACK,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,BLACK,DRKGRY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,DRKGRY,DRKGRY,BLACK,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::chip
#endif
