#ifndef CHIPPIE_RIGHT_HPP
#define CHIPPIE_RIGHT_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::chippie_right {

namespace {

inline constexpr std::array tile_data { embp::pfold(
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LGREY,BLACK,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,YELLOW,YELLOW,YELLOW,LYELLOW,LYELLOW,LYELLOW,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,YELLOW,LYELLOW,LYELLOW,LYELLOW,LYELLOW,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,LYELLOW,BLACK,BLACK,LYELLOW,BLACK,LGREY,LGREY,LGREY,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,LYELLOW,LYELLOW,LYELLOW,LYELLOW,BLACK,LGREY,LGREY,BLACK,LYELLOW,BLACK,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LYELLOW,LYELLOW,LYELLOW,LYELLOW,BLACK,LGREY,LGREY,BLACK,CYAN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,BLACK,CYAN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LCYAN,CYAN,LCYAN,BLACK,CYAN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,CYAN,CYAN,CYAN,CYAN,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,CYAN,CYAN,CYAN,CYAN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,CYAN,BLACK,CYAN,CYAN,CYAN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,CYAN,BLACK,CYAN,CYAN,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,CYAN,BLACK,BLACK,LYELLOW,BLACK,GREEN,GREEN,GREEN,GREEN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,CYAN,CYAN,CYAN,BLACK,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,DRKGRY,DRKGRY,BLACK,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,GREEN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,GREEN,GREEN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,DRKGRY,GREEN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,DRKGRY,DRKGRY,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,DRKGRY,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 1,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::chippie_right
#endif
