#ifndef CHIPPIE_DOWN_HPP
#define CHIPPIE_DOWN_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::chippie_down {

namespace {

inline constexpr std::array tile_data { embp::pfold(
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,YELLOW,YELLOW,YELLOW,LYELLOW,LYELLOW,YELLOW,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,YELLOW,LYELLOW,LYELLOW,LYELLOW,LYELLOW,LYELLOW,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LYELLOW,BLACK,LYELLOW,LYELLOW,BLACK,LYELLOW,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LYELLOW,LYELLOW,BLACK,BLACK,LYELLOW,LYELLOW,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LYELLOW,LYELLOW,LYELLOW,LYELLOW,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,BLACK,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,LYELLOW,BLACK,LGREY,BLACK,CYAN,LCYAN,CYAN,LCYAN,CYAN,CYAN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,LYELLOW,BLACK,BLACK,CYAN,BLACK,CYAN,CYAN,CYAN,CYAN,BLACK,CYAN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,BLACK,CYAN,BLACK,BLACK,BLACK,LCYAN,CYAN,CYAN,CYAN,DRKGRY,BLACK,CYAN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,BLACK,CYAN,BLACK,LGREY,BLACK,CYAN,CYAN,CYAN,CYAN,BLACK,LGREY,BLACK,CYAN,BLACK,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LGREY,LGREY,BLACK,LCYAN,CYAN,CYAN,CYAN,DRKGRY,LGREY,LGREY,BLACK,LYELLOW,BLACK,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,CYAN,CYAN,CYAN,CYAN,BLACK,LGREY,LGREY,LGREY,BLACK,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,GREEN,BLACK,GREEN,GREEN,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LGREEN,BLACK,GREEN,GREEN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,GREEN,BLACK,GREEN,GREEN,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LGREEN,BLACK,GREEN,GREEN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,GREEN,BLACK,BLACK,GREEN,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,DRKGRY,LGREY,BLACK,BLACK,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,BLACK,LGREY,LGREY,BLACK,DRKGRY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 1,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::chippie_down
#endif
