#ifndef CLONER_CYAN_STICK_BALL_HPP
#define CLONER_CYAN_STICK_BALL_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::cloner_cyan_stick_ball {

namespace {

inline constexpr std::array tile_data { embp::pfold(
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
LGREY,LGREY,DRKGRY,BLACK,BLACK,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,DRKGRY,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,BLACK,DRKGRY,DRKGRY,DRKGRY,BLACK,DRKGRY,DRKGRY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,BLACK,DRKGRY,DRKGRY,DRKGRY,BLACK,BLACK,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,BLACK,DRKGRY,BLACK,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,DRKGRY,DRKGRY,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,DRKGRY,BLACK,CYAN,CYAN,CYAN,WHITE,WHITE,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,DRKGRY,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,BLACK,CYAN,CYAN,WHITE,WHITE,WHITE,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,DRKGRY,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,BLACK,CYAN,CYAN,CYAN,WHITE,WHITE,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,BLACK,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,BLACK,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,BLACK,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,DRKGRY,BLACK,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,BLACK,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,DRKGRY,CYAN,BLACK,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,BLACK,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,BLACK,DRKGRY,CYAN,DRKGRY,BLACK,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,DRKGRY,BLACK,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,DRKGRY,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,BLACK,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,DRKGRY,DRKGRY,DRKGRY,BLACK,BLACK,DRKGRY,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,DRKGRY,DRKGRY,BLACK,CYAN,CYAN,CYAN,CYAN,DRKGRY,CYAN,DRKGRY,BLACK,DRKGRY,DRKGRY,DRKGRY,BLACK,DRKGRY,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,BLACK,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,BLACK,DRKGRY,DRKGRY,DRKGRY,BLACK,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,DRKGRY,BLACK,DRKGRY,DRKGRY,DRKGRY,BLACK,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,DRKGRY,DRKGRY,DRKGRY,BLACK,DRKGRY,BLACK,
LGREY,LGREY,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,DRKGRY,DRKGRY,BLACK,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,BLACK,BLACK,DRKGRY,BLACK,
LGREY,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::cloner_cyan_stick_ball
#endif
