#ifndef CLONER_MOVEABLE_BLOCK_HPP
#define CLONER_MOVEABLE_BLOCK_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::cloner_moveable_block {

namespace {

inline constexpr std::array tile_data { embp::pfold(
YELLOW,LYELLOW,YELLOW,LYELLOW,YELLOW,LYELLOW,YELLOW,LYELLOW,YELLOW,LYELLOW,YELLOW,LYELLOW,YELLOW,LYELLOW,YELLOW,LYELLOW,YELLOW,LYELLOW,YELLOW,LYELLOW,YELLOW,LYELLOW,YELLOW,BLACK,
LYELLOW,YELLOW,LYELLOW,YELLOW,LYELLOW,YELLOW,LYELLOW,YELLOW,LYELLOW,YELLOW,LYELLOW,YELLOW,LYELLOW,YELLOW,LYELLOW,YELLOW,LYELLOW,YELLOW,LYELLOW,YELLOW,LYELLOW,YELLOW,BLACK,YELLOW,
YELLOW,LYELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,
LYELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,YELLOW,
YELLOW,LYELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,
LYELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,YELLOW,
YELLOW,LYELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,
LYELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,DRKGRY,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,YELLOW,
YELLOW,LYELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,DRKGRY,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,DRKGRY,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,
LYELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,DRKGRY,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,DRKGRY,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,YELLOW,
YELLOW,LYELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,DRKGRY,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,DRKGRY,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,
LYELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,DRKGRY,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,DRKGRY,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,YELLOW,
YELLOW,LYELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,DRKGRY,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,DRKGRY,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,
LYELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,DRKGRY,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,DRKGRY,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,YELLOW,
YELLOW,LYELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,DRKGRY,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,DRKGRY,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,
LYELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,DRKGRY,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,DRKGRY,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,YELLOW,
YELLOW,LYELLOW,YELLOW,YELLOW,YELLOW,YELLOW,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,
LYELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,YELLOW,
YELLOW,LYELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,
LYELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,YELLOW,
YELLOW,LYELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,
LYELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,YELLOW,
YELLOW,BLACK,YELLOW,BLACK,YELLOW,BLACK,YELLOW,BLACK,YELLOW,BLACK,YELLOW,BLACK,YELLOW,BLACK,YELLOW,BLACK,YELLOW,BLACK,YELLOW,BLACK,YELLOW,BLACK,YELLOW,BLACK,
BLACK,YELLOW,BLACK,YELLOW,BLACK,YELLOW,BLACK,YELLOW,BLACK,YELLOW,BLACK,YELLOW,BLACK,YELLOW,BLACK,YELLOW,BLACK,YELLOW,BLACK,YELLOW,BLACK,YELLOW,BLACK,YELLOW
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::cloner_moveable_block
#endif
