#ifndef CLONER_FROG_MONSTER_HPP
#define CLONER_FROG_MONSTER_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::cloner_frog_monster {

namespace {

inline constexpr std::array tile_data { embp::pfold(
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
LGREY,LGREY,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,RED,LRED,RED,LRED,RED,LRED,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,RED,LRED,RED,LRED,RED,LRED,RED,LRED,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,LRED,DRKGRY,RED,DRKGRY,LRED,RED,LRED,RED,LRED,RED,LRED,RED,DRKGRY,RED,DRKGRY,RED,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,LRED,RED,LRED,RED,LRED,RED,LRED,RED,LRED,RED,LRED,RED,RED,RED,RED,RED,LRED,RED,LGREY,DRKGRY,BLACK,
LGREY,LGREY,LRED,RED,LRED,RED,LRED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,LRED,RED,BLACK,DRKGRY,
LGREY,LGREY,RED,LRED,RED,LRED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,DRKGRY,BLACK,
LGREY,RED,LRED,RED,LRED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,DRKGRY,
LGREY,RED,RED,LRED,RED,RED,RED,RED,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,RED,RED,RED,RED,RED,RED,RED,BLACK,
LGREY,BLACK,RED,RED,RED,RED,RED,RED,GREEN,GREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,RED,RED,RED,RED,RED,RED,BLACK,DRKGRY,
LGREY,LGREY,RED,RED,RED,RED,RED,RED,RED,GREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,RED,RED,RED,RED,RED,RED,RED,DRKGRY,BLACK,
LGREEN,LGREEN,BLACK,RED,RED,LGREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,GREEN,LGREEN,RED,RED,LGREY,LGREEN,LGREEN,
GREEN,LGREEN,DRKGRY,RED,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,RED,LGREY,LGREEN,GREEN,
GREEN,GREEN,GREEN,GREEN,GREEN,RED,RED,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,RED,RED,GREEN,GREEN,GREEN,GREEN,GREEN,
LGREY,GREEN,GREEN,GREEN,DRKGRY,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,DRKGRY,GREEN,GREEN,GREEN,BLACK,
LGREY,LGREY,BLACK,DRKGRY,DRKGRY,LGREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,GREEN,LGREEN,DRKGRY,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,LGREEN,GREEN,GREEN,GREEN,DRKGRY,LGREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,DRKGRY,GREEN,GREEN,GREEN,LGREEN,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,LGREEN,GREEN,GREEN,DRKGRY,DRKGRY,DRKGRY,LGREEN,LGREEN,LGREEN,LGREEN,DRKGRY,DRKGRY,DRKGRY,GREEN,GREEN,LGREEN,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,LGREEN,GREEN,GREEN,GREEN,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,GREEN,GREEN,GREEN,LGREEN,LGREY,DRKGRY,BLACK,
LGREY,LGREEN,LGREEN,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,GREEN,GREEN,GREEN,LGREEN,LGREEN,DRKGRY,
LGREY,GREEN,GREEN,GREEN,GREEN,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,GREEN,GREEN,GREEN,GREEN,BLACK,
LGREY,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::cloner_frog_monster
#endif
