#ifndef CLONER_CENTIPEDE_UP_HPP
#define CLONER_CENTIPEDE_UP_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::cloner_centipede_up {

namespace {

inline constexpr std::array tile_data { embp::pfold(
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
LGREY,LGREY,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,BLACK,DRKGRY,DRKGRY,BLACK,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,LYELLOW,LYELLOW,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,LYELLOW,YELLOW,YELLOW,YELLOW,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,DRKGRY,RED,DRKGRY,DRKGRY,BLACK,LYELLOW,LYELLOW,LYELLOW,LYELLOW,LYELLOW,YELLOW,BLACK,DRKGRY,DRKGRY,RED,DRKGRY,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,RED,DRKGRY,DRKGRY,BLACK,LYELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,DRKGRY,DRKGRY,RED,DRKGRY,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,DRKGRY,DRKGRY,RED,DRKGRY,DRKGRY,BLACK,LYELLOW,LYELLOW,YELLOW,YELLOW,BLACK,DRKGRY,DRKGRY,RED,DRKGRY,DRKGRY,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,RED,RED,RED,BLACK,YELLOW,YELLOW,BLACK,RED,RED,RED,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,LYELLOW,YELLOW,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,DRKGRY,DRKGRY,RED,RED,RED,BLACK,LYELLOW,LYELLOW,YELLOW,YELLOW,BLACK,RED,RED,RED,DRKGRY,DRKGRY,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,RED,DRKGRY,DRKGRY,BLACK,LYELLOW,BLACK,BLACK,BLACK,BLACK,YELLOW,BLACK,DRKGRY,DRKGRY,RED,DRKGRY,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,LYELLOW,LYELLOW,LYELLOW,LYELLOW,LYELLOW,LYELLOW,YELLOW,YELLOW,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,RED,BLACK,LYELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,RED,DRKGRY,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,RED,DRKGRY,BLACK,LYELLOW,LYELLOW,LYELLOW,LYELLOW,LYELLOW,LYELLOW,LYELLOW,LYELLOW,YELLOW,YELLOW,BLACK,DRKGRY,RED,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,RED,DRKGRY,DRKGRY,DRKGRY,BLACK,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,YELLOW,BLACK,DRKGRY,DRKGRY,RED,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,RED,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,BLACK,LYELLOW,LYELLOW,LYELLOW,YELLOW,BLACK,BLACK,DRKGRY,DRKGRY,DRKGRY,RED,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,YELLOW,YELLOW,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,
LGREY,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::cloner_centipede_up
#endif
