#ifndef CLONER_FIRE_DANCER_HPP
#define CLONER_FIRE_DANCER_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::cloner_fire_dancer {

namespace {

inline constexpr std::array tile_data { embp::pfold(
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
LGREY,LGREY,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,
LGREY,LGREY,BLACK,RED,RED,RED,RED,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,RED,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,RED,RED,RED,RED,LRED,LRED,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,RED,RED,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,DRKGRY,LYELLOW,RED,RED,RED,LRED,LRED,LRED,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,YELLOW,LYELLOW,RED,RED,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,YELLOW,YELLOW,RED,RED,RED,LRED,LRED,RED,LRED,LRED,LRED,YELLOW,YELLOW,RED,RED,RED,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,DRKGRY,DRKGRY,YELLOW,YELLOW,YELLOW,RED,RED,LRED,LRED,LRED,LRED,YELLOW,LYELLOW,RED,RED,RED,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LRED,LYELLOW,YELLOW,YELLOW,YELLOW,RED,LRED,LRED,RED,YELLOW,YELLOW,RED,RED,LRED,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,DRKGRY,DRKGRY,LRED,LRED,RED,RED,LYELLOW,YELLOW,YELLOW,YELLOW,RED,YELLOW,RED,RED,LRED,LRED,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LRED,LRED,LRED,YELLOW,YELLOW,LRED,YELLOW,LYELLOW,YELLOW,YELLOW,RED,LRED,LRED,DRKGRY,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,DRKGRY,DRKGRY,RED,LRED,LRED,YELLOW,YELLOW,RED,RED,LRED,YELLOW,RED,LRED,LRED,LRED,DRKGRY,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,LRED,LRED,LRED,RED,YELLOW,LRED,RED,RED,YELLOW,YELLOW,LRED,LRED,RED,DRKGRY,DRKGRY,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,DRKGRY,LRED,LRED,RED,YELLOW,YELLOW,LYELLOW,YELLOW,LRED,YELLOW,YELLOW,LRED,LRED,LRED,DRKGRY,DRKGRY,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,LRED,LRED,RED,RED,YELLOW,RED,YELLOW,YELLOW,YELLOW,LYELLOW,RED,RED,LRED,LRED,DRKGRY,DRKGRY,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,DRKGRY,LRED,RED,RED,YELLOW,YELLOW,RED,LRED,LRED,RED,YELLOW,YELLOW,YELLOW,YELLOW,LRED,DRKGRY,DRKGRY,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,RED,RED,RED,YELLOW,LYELLOW,LRED,LRED,LRED,LRED,RED,RED,YELLOW,LYELLOW,YELLOW,DRKGRY,DRKGRY,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,RED,RED,RED,YELLOW,YELLOW,LRED,LRED,LRED,RED,LRED,LRED,RED,RED,RED,YELLOW,YELLOW,DRKGRY,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,RED,RED,LYELLOW,YELLOW,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LRED,LRED,LRED,RED,RED,RED,LYELLOW,DRKGRY,DRKGRY,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,RED,RED,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LRED,LRED,RED,RED,RED,RED,DRKGRY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,RED,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,RED,RED,RED,RED,LGREY,DRKGRY,BLACK,
LGREY,LGREY,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,
LGREY,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::cloner_fire_dancer
#endif
