#ifndef DIRT_HPP
#define DIRT_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::dirt {

namespace {

inline constexpr std::array tile_data { embp::pfold(
DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,
BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,
DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,
BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,
DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,
BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,
DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,
BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,
DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,
BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,
DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,
BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,
DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,
BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,
DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,
BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,
DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,
BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,
DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,
BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,
DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,
BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,
DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,
BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY,BROWN,DRKGRY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::dirt
#endif
