#ifndef FIRE_DANCER_HPP
#define FIRE_DANCER_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::fire_dancer {

namespace {

inline constexpr std::array tile_data { embp::pfold(
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,RED,RED,RED,RED,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,RED,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,RED,RED,RED,RED,LRED,LRED,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,RED,RED,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LYELLOW,RED,RED,RED,LRED,LRED,LRED,LGREY,LGREY,LGREY,LGREY,LGREY,YELLOW,LYELLOW,RED,RED,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,YELLOW,YELLOW,RED,RED,RED,LRED,LRED,RED,LRED,LRED,LRED,YELLOW,YELLOW,RED,RED,RED,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,YELLOW,YELLOW,YELLOW,RED,RED,LRED,LRED,LRED,LRED,YELLOW,LYELLOW,RED,RED,RED,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LRED,LYELLOW,YELLOW,YELLOW,YELLOW,RED,LRED,LRED,RED,YELLOW,YELLOW,RED,RED,LRED,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LRED,LRED,RED,RED,LYELLOW,YELLOW,YELLOW,YELLOW,RED,YELLOW,RED,RED,LRED,LRED,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LRED,LRED,LRED,YELLOW,YELLOW,LRED,YELLOW,LYELLOW,YELLOW,YELLOW,RED,LRED,LRED,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,RED,LRED,LRED,YELLOW,YELLOW,RED,RED,LRED,YELLOW,RED,LRED,LRED,LRED,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LRED,LRED,LRED,RED,YELLOW,LRED,RED,RED,YELLOW,YELLOW,LRED,LRED,RED,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LRED,LRED,RED,YELLOW,YELLOW,LYELLOW,YELLOW,LRED,YELLOW,YELLOW,LRED,LRED,LRED,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LRED,LRED,RED,RED,YELLOW,RED,YELLOW,YELLOW,YELLOW,LYELLOW,RED,RED,LRED,LRED,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LRED,RED,RED,YELLOW,YELLOW,RED,LRED,LRED,RED,YELLOW,YELLOW,YELLOW,YELLOW,LRED,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,RED,RED,RED,YELLOW,LYELLOW,LRED,LRED,LRED,LRED,RED,RED,YELLOW,LYELLOW,YELLOW,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,RED,RED,RED,YELLOW,YELLOW,LRED,LRED,LRED,RED,LRED,LRED,RED,RED,RED,YELLOW,YELLOW,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,RED,RED,LYELLOW,YELLOW,LGREY,LGREY,LGREY,LGREY,LGREY,LRED,LRED,LRED,RED,RED,RED,LYELLOW,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,RED,RED,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LRED,LRED,RED,RED,RED,RED,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,RED,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,RED,RED,RED,RED,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 1,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::fire_dancer
#endif
