#ifndef FIRE_BOOTS_HPP
#define FIRE_BOOTS_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::fire_boots {

namespace {

inline constexpr std::array tile_data { embp::pfold(
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,DRKGRY,DRKGRY,LGREY,LGREY,BLACK,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,BLACK,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,BLACK,BLACK,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BROWN,BLACK,BLACK,BLACK,BLACK,BLACK,BROWN,BLACK,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,YELLOW,RED,YELLOW,BROWN,LRED,BROWN,LRED,BLACK,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,YELLOW,RED,YELLOW,BROWN,LRED,BROWN,LRED,BROWN,BLACK,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,RED,YELLOW,BROWN,LRED,BROWN,LRED,BROWN,LRED,BROWN,BLACK,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,YELLOW,RED,YELLOW,BROWN,LRED,BROWN,LRED,BROWN,LRED,BLACK,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,YELLOW,RED,YELLOW,BROWN,LRED,BROWN,LRED,BROWN,LRED,BROWN,BLACK,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,YELLOW,RED,YELLOW,BROWN,LRED,BROWN,LRED,BROWN,LRED,BROWN,LRED,BLACK,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,BROWN,YELLOW,RED,YELLOW,BROWN,LRED,BROWN,LRED,BROWN,LRED,BROWN,LRED,BROWN,BLACK,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,BLACK,BLACK,YELLOW,RED,YELLOW,RED,YELLOW,BROWN,LRED,BROWN,LRED,BROWN,LRED,BROWN,LRED,BLACK,BLACK,BLACK,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,BLACK,YELLOW,RED,YELLOW,RED,YELLOW,BROWN,LRED,BROWN,LRED,BROWN,LRED,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,BLACK,YELLOW,RED,YELLOW,RED,YELLOW,BROWN,LRED,BROWN,LRED,BROWN,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,BLACK,BROWN,LRED,BROWN,LRED,BROWN,LRED,BROWN,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,BLACK,BLACK,BROWN,LRED,BROWN,LRED,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::fire_boots
#endif
