#ifndef FLIPPERS_HPP
#define FLIPPERS_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::flippers {

namespace {

inline constexpr std::array tile_data { embp::pfold(
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LGREY,CYAN,LCYAN,LCYAN,BLACK,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LGREY,CYAN,LGREY,CYAN,LCYAN,LCYAN,BLACK,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,CYAN,LGREY,CYAN,LCYAN,CYAN,LCYAN,BLACK,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,CYAN,LGREY,CYAN,LGREY,BLACK,BLACK,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LCYAN,LCYAN,BLACK,BLACK,BLACK,BLACK,CYAN,BLACK,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,CYAN,CYAN,BLACK,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,CYAN,CYAN,CYAN,BLACK,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,CYAN,CYAN,CYAN,BLACK,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,BLACK,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,LGREY,LGREY,LGREY,DRKGRY,
WHITE,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,BLACK,LCYAN,WHITE,WHITE,CYAN,CYAN,LCYAN,CYAN,LCYAN,LCYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,BLACK,CYAN,CYAN,CYAN,LCYAN,LCYAN,WHITE,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,BLACK,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,CYAN,LCYAN,LCYAN,WHITE,CYAN,CYAN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,BLACK,LCYAN,WHITE,WHITE,CYAN,LCYAN,LCYAN,WHITE,CYAN,CYAN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,BLACK,CYAN,CYAN,LCYAN,WHITE,WHITE,CYAN,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,CYAN,CYAN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::flippers
#endif
