#ifndef FROG_LEFT_HPP
#define FROG_LEFT_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::frog_left {

namespace {

inline constexpr std::array tile_data { embp::pfold(
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,WHITE,WHITE,WHITE,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LRED,RED,LRED,RED,LRED,RED,WHITE,BLACK,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LRED,RED,RED,RED,RED,RED,LRED,RED,LRED,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,RED,RED,RED,RED,RED,RED,RED,RED,RED,LRED,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,WHITE,RED,RED,RED,RED,RED,RED,RED,RED,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,WHITE,BLACK,WHITE,RED,RED,RED,RED,RED,LRED,RED,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,WHITE,BLACK,WHITE,BLACK,WHITE,RED,RED,RED,RED,LRED,LGREY,LGREY,LGREY,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,WHITE,BLACK,WHITE,BLACK,RED,RED,RED,RED,LGREY,LGREY,LGREY,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,RED,RED,RED,RED,GREEN,LGREY,LGREY,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,RED,RED,RED,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,RED,RED,RED,BLACK,DRKGRY,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,WHITE,BLACK,RED,RED,RED,BLACK,DRKGRY,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,WHITE,RED,RED,RED,RED,BLACK,DRKGRY,GREEN,LGREEN,LGREEN,GREEN,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,WHITE,BLACK,RED,RED,LRED,RED,LRED,GREEN,GREEN,GREEN,LGREEN,GREEN,LGREEN,GREEN,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,RED,RED,RED,LRED,RED,LGREY,LGREY,GREEN,DRKGRY,BLACK,GREEN,LGREEN,GREEN,LGREEN,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LRED,RED,LRED,RED,LGREY,LGREY,GREEN,GREEN,GREEN,BLACK,LGREEN,GREEN,LGREEN,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,GREEN,GREEN,DRKGRY,BLACK,GREEN,LGREEN,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,GREEN,LGREY,LGREY,LGREY,GREEN,GREEN,GREEN,BLACK,LGREEN,GREEN,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,GREEN,GREEN,GREEN,LGREEN,GREEN,GREEN,BLACK,LGREEN,GREEN,LGREEN,GREEN,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,LGREEN,GREEN,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREEN,GREEN,LGREEN,GREEN,LGREEN,GREEN,LGREEN,GREEN,DRKGRY,DRKGRY,LGREY,LGREY,DRKGRY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 1,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::frog_left
#endif
