#ifndef FROG_RIGHT_HPP
#define FROG_RIGHT_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::frog_right {

namespace {

inline constexpr std::array tile_data { embp::pfold(
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,WHITE,WHITE,WHITE,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,WHITE,BLACK,WHITE,RED,LRED,RED,LRED,RED,LRED,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,WHITE,LRED,RED,LRED,RED,RED,RED,RED,RED,LRED,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LRED,RED,RED,RED,RED,RED,RED,RED,RED,RED,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,RED,RED,RED,RED,RED,RED,RED,RED,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,RED,LRED,RED,RED,RED,RED,RED,WHITE,BLACK,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,LRED,RED,RED,RED,RED,WHITE,BLACK,WHITE,BLACK,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,RED,RED,RED,RED,BLACK,WHITE,BLACK,WHITE,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,GREEN,GREEN,GREEN,LGREY,LGREY,GREEN,RED,RED,RED,RED,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,RED,RED,RED,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,GREEN,GREEN,GREEN,DRKGRY,BLACK,RED,RED,RED,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,GREEN,GREEN,GREEN,DRKGRY,BLACK,RED,RED,RED,BLACK,WHITE,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,GREEN,LGREEN,LGREEN,GREEN,DRKGRY,BLACK,RED,RED,RED,RED,WHITE,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,GREEN,LGREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,LRED,RED,LRED,RED,RED,BLACK,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREEN,GREEN,LGREEN,GREEN,BLACK,DRKGRY,GREEN,LGREY,LGREY,RED,LRED,RED,RED,RED,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREEN,GREEN,LGREEN,BLACK,GREEN,GREEN,GREEN,LGREY,LGREY,RED,LRED,RED,LRED,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREEN,GREEN,BLACK,DRKGRY,GREEN,GREEN,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,GREEN,LGREEN,BLACK,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,GREEN,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,GREEN,LGREEN,GREEN,LGREEN,BLACK,GREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,GREEN,LGREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,GREEN,LGREEN,GREEN,LGREEN,GREEN,LGREEN,GREEN,LGREEN,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 1,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::frog_right
#endif
