#ifndef FROG_DOWN_HPP
#define FROG_DOWN_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::frog_down {

namespace {

inline constexpr std::array tile_data { embp::pfold(
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,WHITE,WHITE,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,WHITE,WHITE,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,WHITE,BLACK,WHITE,LGREY,RED,LRED,RED,LRED,RED,LRED,LGREY,WHITE,BLACK,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LRED,RED,LRED,RED,LRED,RED,RED,RED,RED,RED,LRED,RED,LRED,RED,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LRED,RED,RED,RED,RED,RED,WHITE,BLACK,WHITE,BLACK,RED,RED,RED,RED,LRED,RED,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LRED,RED,RED,RED,RED,RED,BLACK,WHITE,BLACK,WHITE,BLACK,WHITE,RED,RED,RED,RED,LRED,RED,LGREY,LGREY,LGREY,
LGREY,LGREY,LRED,RED,RED,RED,RED,WHITE,WHITE,BLACK,WHITE,BLACK,WHITE,BLACK,WHITE,WHITE,WHITE,RED,RED,RED,LRED,RED,LGREY,LGREY,
LGREY,LGREY,RED,RED,RED,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,BLACK,WHITE,RED,RED,RED,LGREY,LGREY,
LGREY,RED,WHITE,BLACK,WHITE,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,BLACK,WHITE,BLACK,WHITE,BLACK,WHITE,BLACK,RED,LGREY,
LGREY,RED,BLACK,BLACK,WHITE,BLACK,WHITE,BLACK,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,BLACK,WHITE,LGREY,RED,LGREY,
LGREY,BLACK,RED,BLACK,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,RED,BLACK,LGREY,
LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,
LGREEN,LGREEN,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,LGREEN,LGREEN,
GREEN,LGREEN,LGREY,BLACK,RED,WHITE,BLACK,BLACK,BLACK,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,BLACK,WHITE,BLACK,RED,BLACK,LGREY,LGREEN,GREEN,
GREEN,GREEN,GREEN,GREEN,BLACK,RED,RED,WHITE,BLACK,WHITE,BLACK,WHITE,BLACK,WHITE,BLACK,WHITE,BLACK,RED,RED,BLACK,GREEN,GREEN,GREEN,GREEN,
LGREY,GREEN,GREEN,GREEN,LGREY,BLACK,BLACK,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,BLACK,BLACK,LGREY,GREEN,GREEN,GREEN,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREEN,GREEN,BLACK,BLACK,BLACK,RED,RED,RED,RED,BLACK,BLACK,BLACK,GREEN,LGREEN,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREEN,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,GREEN,GREEN,GREEN,LGREEN,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREEN,GREEN,GREEN,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,GREEN,GREEN,LGREEN,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREEN,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,LGREY,GREEN,GREEN,GREEN,LGREEN,LGREY,LGREY,LGREY,
LGREY,LGREEN,LGREEN,GREEN,GREEN,GREEN,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,GREEN,GREEN,GREEN,LGREEN,LGREEN,DRKGRY,
LGREY,GREEN,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,GREEN,GREEN,GREEN,GREEN,DRKGRY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 1,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::frog_down
#endif
