#ifndef FROG_UP_HPP
#define FROG_UP_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::frog_up {

namespace {

inline constexpr std::array tile_data { embp::pfold(
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,LGREY,RED,LRED,RED,LRED,RED,LRED,LGREY,DRKGRY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,RED,LRED,RED,LRED,RED,LRED,RED,LRED,DRKGRY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LRED,DRKGRY,RED,DRKGRY,LRED,RED,LRED,RED,LRED,RED,LRED,RED,DRKGRY,RED,DRKGRY,RED,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LRED,RED,LRED,RED,LRED,RED,LRED,RED,LRED,RED,LRED,RED,RED,RED,RED,RED,LRED,RED,LGREY,LGREY,LGREY,
LGREY,LGREY,LRED,RED,LRED,RED,LRED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,LRED,RED,LGREY,LGREY,
LGREY,LGREY,RED,LRED,RED,LRED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,LGREY,LGREY,
LGREY,RED,LRED,RED,LRED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,LGREY,
LGREY,RED,RED,LRED,RED,RED,RED,RED,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,RED,RED,RED,RED,RED,RED,RED,LGREY,
LGREY,BLACK,RED,RED,RED,RED,RED,RED,GREEN,GREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,RED,RED,RED,RED,RED,RED,BLACK,LGREY,
LGREY,LGREY,RED,RED,RED,RED,RED,RED,RED,GREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,RED,RED,RED,RED,RED,RED,RED,LGREY,LGREY,
LGREEN,LGREEN,LGREY,RED,RED,LGREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,GREEN,LGREEN,RED,RED,LGREY,LGREEN,LGREEN,
GREEN,LGREEN,LGREY,RED,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,RED,LGREY,LGREEN,GREEN,
GREEN,GREEN,GREEN,GREEN,GREEN,RED,RED,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,RED,RED,GREEN,GREEN,GREEN,GREEN,GREEN,
LGREY,GREEN,GREEN,GREEN,LGREY,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,LGREY,GREEN,GREEN,GREEN,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,GREEN,LGREEN,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREEN,GREEN,GREEN,GREEN,LGREY,LGREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREY,GREEN,GREEN,GREEN,LGREEN,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREEN,GREEN,GREEN,LGREY,LGREY,LGREY,LGREEN,LGREEN,LGREEN,LGREEN,LGREY,LGREY,LGREY,GREEN,GREEN,LGREEN,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREEN,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,LGREY,GREEN,GREEN,GREEN,LGREEN,LGREY,LGREY,LGREY,
LGREY,LGREEN,LGREEN,GREEN,GREEN,GREEN,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,GREEN,GREEN,GREEN,LGREEN,LGREEN,DRKGRY,
LGREY,GREEN,GREEN,GREEN,GREEN,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,GREEN,GREEN,GREEN,GREEN,DRKGRY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 1,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::frog_up
#endif
