#ifndef GRAVEL_HPP
#define GRAVEL_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::gravel {

namespace {

inline constexpr std::array tile_data { embp::pfold(
LGREY,LGREY,LGREY,BLACK,LGREY,BLACK,BLACK,LGREY,LGREY,BLACK,LGREY,BLACK,BLACK,WHITE,BLACK,BLACK,BLACK,WHITE,BLACK,BLACK,BLACK,BLACK,LGREY,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,BLACK,LGREY,BLACK,BLACK,BLACK,WHITE,BLACK,BLACK,BLACK,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
WHITE,BLACK,BLACK,BLACK,BLACK,LGREY,BLACK,BLACK,BLACK,BLACK,LGREY,BLACK,LGREY,BLACK,BLACK,BLACK,BLACK,LGREY,BLACK,BLACK,WHITE,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,WHITE,BLACK,LGREY,LGREY,BLACK,WHITE,BLACK,BLACK,LGREY,BLACK,BLACK,WHITE,BLACK,LGREY,LGREY,LGREY,BLACK,BLACK,WHITE,LGREY,BLACK,
BLACK,BLACK,BLACK,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,BLACK,BLACK,BLACK,BLACK,LGREY,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,BLACK,LGREY,BLACK,BLACK,LGREY,BLACK,BLACK,BLACK,LGREY,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,BLACK,BLACK,
LGREY,BLACK,WHITE,BLACK,LGREY,BLACK,WHITE,BLACK,LGREY,LGREY,BLACK,LGREY,BLACK,LGREY,WHITE,BLACK,BLACK,BLACK,LGREY,BLACK,LGREY,BLACK,LGREY,BLACK,
BLACK,BLACK,LGREY,BLACK,BLACK,BLACK,LGREY,BLACK,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,BLACK,WHITE,WHITE,WHITE,BLACK,LGREY,BLACK,BLACK,
LGREY,BLACK,LGREY,BLACK,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,WHITE,BLACK,LGREY,WHITE,WHITE,BLACK,BLACK,BLACK,WHITE,LGREY,LGREY,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,BLACK,BLACK,BLACK,WHITE,BLACK,BLACK,LGREY,BLACK,BLACK,BLACK,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,LGREY,BLACK,WHITE,BLACK,BLACK,WHITE,BLACK,BLACK,BLACK,BLACK,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,BLACK,LGREY,LGREY,
BLACK,BLACK,WHITE,BLACK,BLACK,BLACK,BLACK,WHITE,BLACK,LGREY,BLACK,BLACK,WHITE,BLACK,BLACK,BLACK,BLACK,WHITE,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,LGREY,BLACK,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,BLACK,BLACK,BLACK,BLACK,LGREY,BLACK,BLACK,LGREY,LGREY,WHITE,LGREY,BLACK,
BLACK,LGREY,WHITE,WHITE,LGREY,WHITE,BLACK,WHITE,BLACK,BLACK,BLACK,LGREY,BLACK,BLACK,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,BLACK,BLACK,BLACK,
LGREY,BLACK,BLACK,BLACK,WHITE,BLACK,BLACK,BLACK,LGREY,BLACK,BLACK,LGREY,WHITE,BLACK,BLACK,LGREY,BLACK,BLACK,BLACK,LGREY,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,LGREY,BLACK,BLACK,BLACK,LGREY,BLACK,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,LGREY,BLACK,BLACK,WHITE,LGREY,
BLACK,LGREY,BLACK,BLACK,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,BLACK,BLACK,BLACK,LGREY,LGREY,BLACK,BLACK,LGREY,BLACK,BLACK,BLACK,
LGREY,BLACK,BLACK,BLACK,BLACK,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,BLACK,BLACK,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,BLACK,BLACK,
LGREY,BLACK,WHITE,BLACK,LGREY,BLACK,BLACK,LGREY,WHITE,BLACK,LGREY,BLACK,BLACK,LGREY,BLACK,BLACK,WHITE,BLACK,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,BLACK,LGREY,BLACK,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,BLACK,BLACK,WHITE,
BLACK,BLACK,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,WHITE,LGREY,BLACK,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,WHITE,
LGREY,WHITE,BLACK,BLACK,WHITE,LGREY,BLACK,LGREY,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,BLACK,BLACK,BLACK,LGREY,
BLACK,LGREY,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,WHITE,LGREY,BLACK,BLACK,BLACK,WHITE,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,BLACK,
BLACK,BLACK,LGREY,WHITE,LGREY,BLACK,LGREY,BLACK,BLACK,LGREY,BLACK,BLACK,BLACK,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,WHITE,BLACK,BLACK
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::gravel
#endif
