#ifndef GREEN_BUTTON_CLEAR_HPP
#define GREEN_BUTTON_CLEAR_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::green_button_clear {

namespace {

inline constexpr std::array tile_data { embp::pfold(
LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,
LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,
GREEN,GREEN,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,DRKGRY,LGREEN,LGREEN,
GREEN,GREEN,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,LGREEN,LGREEN,
LGREEN,LGREEN,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,GREEN,GREEN,
LGREEN,LGREEN,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,GREEN,GREEN,
LGREEN,LGREEN,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,GREEN,GREEN,
LGREEN,LGREEN,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,GREEN,GREEN,
GREEN,GREEN,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,LGREEN,LGREEN,
GREEN,GREEN,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,LGREEN,LGREEN,
GREEN,GREEN,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,LGREEN,LGREEN,
LGREEN,LGREEN,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,GREEN,GREEN,
LGREEN,LGREEN,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,GREEN,GREEN,
LGREEN,LGREEN,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,GREEN,GREEN,
GREEN,GREEN,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,LGREEN,LGREEN,
GREEN,GREEN,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,LGREEN,LGREEN,
GREEN,GREEN,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,LGREEN,LGREEN,
LGREEN,LGREEN,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,GREEN,GREEN,
LGREEN,LGREEN,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,GREEN,GREEN,
LGREEN,LGREEN,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,GREEN,GREEN,
GREEN,GREEN,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,LGREEN,LGREEN,
GREEN,GREEN,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREEN,LGREEN,
LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,
LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::green_button_clear
#endif
