#ifndef GREEN_DOOR_HPP
#define GREEN_DOOR_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::green_door {

namespace {

inline constexpr std::array tile_data { embp::pfold(
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,GREEN,GREEN,BLACK,BLACK,GREEN,GREEN,BLACK,BLACK,GREEN,GREEN,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,GREEN,GREEN,BLACK,BLACK,GREEN,GREEN,BLACK,BLACK,GREEN,GREEN,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,
LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,
LGREY,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::green_door
#endif
