#ifndef ICE_HPP
#define ICE_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::ice {

namespace {

inline constexpr std::array tile_data { embp::pfold(
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LCYAN,LCYAN,CYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LCYAN,CYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
CYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,
LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,
LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,
LCYAN,CYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,
CYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,
LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,CYAN,LCYAN,
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::ice
#endif
