#ifndef ICE_SKATES_HPP
#define ICE_SKATES_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::ice_skates {

namespace {

inline constexpr std::array tile_data { embp::pfold(
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,DRKGRY,DRKGRY,LGREY,LGREY,BLACK,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,BLACK,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,BLACK,BLACK,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LCYAN,BLACK,BLACK,BLACK,BLACK,BLACK,CYAN,BLACK,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,CYAN,CYAN,BLACK,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,CYAN,BLACK,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,CYAN,CYAN,CYAN,BLACK,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,WHITE,LCYAN,LCYAN,LCYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,BLACK,BLACK,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,BLACK,BLACK,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,BLACK,WHITE,LCYAN,LCYAN,LCYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,BLACK,DRKGRY,DRKGRY,
WHITE,LGREY,BLACK,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,BLACK,BLACK,BLACK,DRKGRY,DRKGRY,
WHITE,LGREY,BLACK,LCYAN,LCYAN,LCYAN,CYAN,CYAN,CYAN,CYAN,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,BLACK,BLACK,DRKGRY,DRKGRY,BLACK,DRKGRY,DRKGRY,
WHITE,LGREY,BLACK,BLACK,CYAN,CYAN,CYAN,CYAN,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,DRKGRY,DRKGRY,BLACK,LGREY,DRKGRY,DRKGRY,
WHITE,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,BLACK,BLACK,DRKGRY,DRKGRY,DRKGRY,BLACK,BLACK,BLACK,LGREY,DRKGRY,DRKGRY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LGREY,LGREY,BLACK,BLACK,BLACK,DRKGRY,DRKGRY,BLACK,BLACK,BLACK,LGREY,DRKGRY,LGREY,DRKGRY,DRKGRY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,DRKGRY,DRKGRY,BLACK,BLACK,BLACK,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,DRKGRY,LGREY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::ice_skates
#endif
