#ifndef ICE_BOTTOMLEFT_HPP
#define ICE_BOTTOMLEFT_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::ice_bottomleft {

namespace {

inline constexpr std::array tile_data { embp::pfold(
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LGREY,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LGREY,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LGREY,LGREY,CYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LGREY,LGREY,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LGREY,LGREY,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LGREY,LGREY,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,
LGREY,LGREY,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,
LGREY,LGREY,LCYAN,WHITE,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,
LGREY,LGREY,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LGREY,LGREY,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LGREY,DRKGRY,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LGREY,LGREY,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LGREY,LGREY,DRKGRY,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,
LGREY,DRKGRY,LGREY,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,
LGREY,LGREY,LGREY,DRKGRY,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,
LGREY,DRKGRY,DRKGRY,LGREY,DRKGRY,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,
LGREY,DRKGRY,LGREY,DRKGRY,LGREY,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,
LGREY,DRKGRY,LGREY,LGREY,WHITE,LGREY,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,
LGREY,DRKGRY,LGREY,LGREY,LGREY,WHITE,LGREY,LGREY,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,
LGREY,DRKGRY,WHITE,WHITE,WHITE,WHITE,LGREY,WHITE,LGREY,LGREY,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,CYAN,LCYAN,LCYAN,CYAN,LCYAN,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,CYAN,LCYAN,LCYAN
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::ice_bottomleft
#endif
