#ifndef ICE_TOPRIGHT_HPP
#define ICE_TOPRIGHT_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::ice_topright {

namespace {

inline constexpr std::array tile_data { embp::pfold(
LCYAN,LCYAN,LCYAN,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,LGREY,LGREY,DRKGRY,LGREY,WHITE,WHITE,WHITE,WHITE,DRKGRY,LGREY,
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,DRKGRY,LGREY,LGREY,DRKGRY,LGREY,LGREY,LGREY,WHITE,LGREY,
LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,DRKGRY,LGREY,DRKGRY,LGREY,LGREY,WHITE,LGREY,
LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,CYAN,DRKGRY,LGREY,DRKGRY,LGREY,WHITE,LGREY,
LCYAN,LCYAN,CYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,DRKGRY,LGREY,DRKGRY,WHITE,LGREY,
LCYAN,CYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,DRKGRY,LGREY,LGREY,LGREY,
CYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LGREY,DRKGRY,LGREY,
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,DRKGRY,LGREY,LGREY,
LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LGREY,LGREY,
LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,CYAN,DRKGRY,LGREY,
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LGREY,LGREY,
LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LGREY,LGREY,
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LGREY,LGREY,
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LGREY,LGREY,
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LGREY,LGREY,
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LGREY,LGREY,
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LGREY,LGREY,
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LGREY,LGREY,
LCYAN,CYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LGREY,
CYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,CYAN,LCYAN,LGREY,
LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,CYAN,LCYAN,LCYAN,CYAN,LCYAN,
LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,WHITE,LCYAN,LCYAN,LCYAN,LCYAN,LCYAN,CYAN,LCYAN,LCYAN
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::ice_topright
#endif
