#ifndef MAGIC_WALL_HPP
#define MAGIC_WALL_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::magic_wall {

namespace {

inline constexpr std::array tile_data { embp::pfold(
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,
LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
LGREY,LGREY,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,BLACK,
LGREY,LGREY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,BLACK,
LGREY,LGREY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,BLACK,
LGREY,LGREY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,BLACK,
LGREY,LGREY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,BLACK,
LGREY,LGREY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,BLACK,
LGREY,LGREY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,BLACK,
LGREY,LGREY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,BLACK,
LGREY,LGREY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,BLACK,
LGREY,LGREY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,BLACK,
LGREY,LGREY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,CYAN,DRKGRY,BLACK,DRKGRY,
LGREY,LGREY,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,
LGREY,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY,BLACK,DRKGRY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::magic_wall
#endif
