#ifndef PORTAL_HPP
#define PORTAL_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::portal {

namespace {

inline constexpr std::array tile_data { embp::pfold(
CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,
CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,
CYAN,CYAN,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,CYAN,CYAN,
CYAN,CYAN,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,CYAN,CYAN,
CYAN,CYAN,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,CYAN,CYAN,
CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,
CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,
CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,
CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,
CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,
CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,
CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,
CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,
CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,
CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,
CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,
CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,
CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,
CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,BLUE,BLUE,BLUE,CYAN,CYAN,
CYAN,CYAN,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,CYAN,CYAN,
CYAN,CYAN,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,CYAN,CYAN,
CYAN,CYAN,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,CYAN,CYAN,
CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,
CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN,CYAN
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::portal
#endif
