#ifndef PUSH_FLOOR_LEFT_HPP
#define PUSH_FLOOR_LEFT_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::push_floor_left {

namespace {

inline constexpr std::array tile_data { embp::pfold(
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::push_floor_left
#endif
