#ifndef PUSH_FLOOR_RIGHT_HPP
#define PUSH_FLOOR_RIGHT_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::push_floor_right {

namespace {

inline constexpr std::array tile_data { embp::pfold(
BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,
WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,
WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,
WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,
WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,WHITE,
WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,
WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,
WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,WHITE,
WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,
WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,
WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,
BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,
BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,
BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,LGREEN,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::push_floor_right
#endif
