#ifndef SOCKET_HPP
#define SOCKET_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::socket {

namespace {

inline constexpr std::array tile_data { embp::pfold(
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,LYELLOW,LYELLOW,DRKGRY,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,LGREY,LYELLOW,LYELLOW,BLACK,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,LYELLOW,LYELLOW,LGREY,DRKGRY,LGREY,BLACK,BLACK,BLACK,BLACK,DRKGRY,LGREY,DRKGRY,LYELLOW,LYELLOW,BLACK,DRKGRY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,BLACK,DRKGRY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,BLACK,DRKGRY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,LYELLOW,LYELLOW,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,LYELLOW,LYELLOW,BLACK,DRKGRY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,LYELLOW,LYELLOW,LGREY,DRKGRY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,DRKGRY,LYELLOW,LYELLOW,BLACK,DRKGRY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,DRKGRY,LGREY,DRKGRY,LGREY,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,DRKGRY,LGREY,DRKGRY,LGREY,BLACK,DRKGRY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,LGREY,DRKGRY,LGREY,DRKGRY,BLACK,DRKGRY,LGREY,LGREY,LGREY,BLACK,LGREY,DRKGRY,LGREY,DRKGRY,BLACK,DRKGRY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,DRKGRY,LGREY,DRKGRY,LGREY,BLACK,DRKGRY,LGREY,LGREY,LGREY,BLACK,DRKGRY,LGREY,DRKGRY,LGREY,BLACK,DRKGRY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,LYELLOW,LYELLOW,LGREY,DRKGRY,BLACK,DRKGRY,LGREY,LGREY,LGREY,BLACK,LGREY,DRKGRY,LYELLOW,LYELLOW,BLACK,DRKGRY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,LYELLOW,LYELLOW,DRKGRY,LGREY,BLACK,DRKGRY,LGREY,LGREY,LGREY,BLACK,DRKGRY,LGREY,LYELLOW,LYELLOW,BLACK,DRKGRY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,LGREY,DRKGRY,LGREY,DRKGRY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,DRKGRY,LGREY,DRKGRY,BLACK,DRKGRY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,BLACK,DRKGRY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,LYELLOW,LYELLOW,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LGREY,DRKGRY,LYELLOW,LYELLOW,BLACK,DRKGRY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,LYELLOW,LYELLOW,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,LYELLOW,LYELLOW,BLACK,DRKGRY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,BLACK,BLACK,BLACK,BLACK,DRKGRY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::socket
#endif
