#ifndef SUCTION_BOOTS_HPP
#define SUCTION_BOOTS_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::suction_boots {

namespace {

inline constexpr std::array tile_data { embp::pfold(
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,DRKGRY,DRKGRY,LGREY,LGREY,BLACK,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,BLACK,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,BLACK,BLACK,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LGREEN,BLACK,BLACK,BLACK,BLACK,BLACK,GREEN,BLACK,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,GREEN,LGREEN,GREEN,LGREEN,GREEN,LGREEN,GREEN,BLACK,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,GREEN,LGREEN,GREEN,LGREEN,GREEN,LGREEN,GREEN,GREEN,BLACK,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LGREEN,GREEN,LGREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,BLACK,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,GREEN,LGREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,GREEN,LGREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,GREEN,LGREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,LGREEN,GREEN,LGREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,BLACK,BLACK,GREEN,LGREEN,GREEN,LGREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,BLACK,GREEN,LGREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,DRKGRY,LGREY,DRKGRY,
WHITE,LGREY,BLACK,GREEN,LGREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,DRKGRY,GREEN,BLACK,DRKGRY,DRKGRY,
WHITE,LGREY,BLACK,LGREEN,GREEN,LGREEN,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,BLACK,BLACK,GREEN,GREEN,GREEN,DRKGRY,GREEN,DRKGRY,BLACK,DRKGRY,DRKGRY,
WHITE,LGREY,BLACK,BLACK,GREEN,GREEN,GREEN,GREEN,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,BLACK,GREEN,GREEN,DRKGRY,GREEN,BLACK,BLACK,DRKGRY,DRKGRY,DRKGRY,
WHITE,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,GREEN,DRKGRY,BLACK,LGREY,DRKGRY,DRKGRY,BLACK,BLACK,BLACK,BLACK,DRKGRY,DRKGRY,DRKGRY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,BLACK,GREEN,GREEN,GREEN,DRKGRY,GREEN,DRKGRY,GREEN,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,GREEN,DRKGRY,GREEN,DRKGRY,BLACK,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,BLACK,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::suction_boots
#endif
