#ifndef THIEF_HPP
#define THIEF_HPP

#include <array>
#include <cstdint>

#include "common/utilities.hpp"
#include "chippie/textures/texture_defs.hpp"

namespace chippie::texture::thief {

namespace {

inline constexpr std::array tile_data { embp::pfold(
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,LGREY,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,LCYAN,BLACK,LGREY,CYAN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,LGREY,LCYAN,LGREY,BLACK,LGREY,CYAN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,BLACK,LCYAN,CYAN,LCYAN,LGREY,LCYAN,LGREY,LCYAN,LGREY,CYAN,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,BLACK,LGREY,LCYAN,LGREY,LCYAN,CYAN,LCYAN,LGREY,LCYAN,LGREY,CYAN,LGREY,BLACK,CYAN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,BLACK,LCYAN,LGREY,LCYAN,LGREY,LCYAN,CYAN,LCYAN,LGREY,CYAN,LGREY,BLACK,LGREY,CYAN,LGREY,BLACK,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,LCYAN,LGREY,LCYAN,LGREY,LCYAN,CYAN,BLACK,BLACK,BLACK,LGREY,CYAN,LGREY,CYAN,BLACK,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,BLACK,LCYAN,LGREY,LCYAN,LGREY,LCYAN,LGREY,LCYAN,LGREY,LCYAN,LGREY,CYAN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,BLACK,LGREY,LCYAN,LGREY,LCYAN,LGREY,LCYAN,LGREY,LCYAN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,BLACK,LGREY,BLACK,BLACK,BLACK,DRKGRY,DRKGRY,BLACK,BLACK,BLACK,LGREY,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,BLACK,WHITE,LGREY,BLACK,BLACK,LGREY,BLACK,DRKGRY,BLACK,BLACK,LGREY,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,WHITE,LGREY,LGREY,WHITE,BLACK,DRKGRY,DRKGRY,DRKGRY,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,LGREY,BLACK,WHITE,WHITE,WHITE,BLACK,BLACK,DRKGRY,LGREY,LGREY,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,BLACK,BLACK,WHITE,WHITE,WHITE,LGREY,DRKGRY,DRKGRY,LGREY,LGREY,BLACK,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,BLACK,CYAN,CYAN,CYAN,WHITE,BLACK,BLACK,LGREY,LGREY,BLACK,BLACK,LCYAN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,BLACK,WHITE,WHITE,CYAN,CYAN,LGREY,LGREY,LGREY,BLACK,BLACK,LCYAN,LGREY,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,LGREY,BLACK,LCYAN,LGREY,WHITE,CYAN,LGREY,LGREY,LGREY,BLACK,LCYAN,LGREY,CYAN,BLACK,LGREY,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,LGREY,LGREY,BLACK,BLACK,LGREY,LCYAN,LGREY,BLACK,BLACK,BLACK,BLACK,BLACK,LCYAN,CYAN,LGREY,BLACK,BLACK,LGREY,LGREY,LGREY,LGREY,DRKGRY,
WHITE,LGREY,BLACK,BLACK,BLACK,CYAN,LCYAN,LGREY,LCYAN,BLACK,CYAN,BLACK,CYAN,BLACK,LCYAN,LGREY,CYAN,BLACK,CYAN,BLACK,BLACK,LGREY,LGREY,DRKGRY,
WHITE,BLACK,BLACK,LCYAN,LGREY,LCYAN,CYAN,LCYAN,BLACK,CYAN,BLACK,CYAN,BLACK,CYAN,BLACK,CYAN,LGREY,BLACK,LGREY,CYAN,BLACK,BLACK,BLACK,DRKGRY,
WHITE,BLACK,LCYAN,LGREY,LCYAN,LGREY,LCYAN,CYAN,LCYAN,BLACK,CYAN,BLACK,CYAN,BLACK,LCYAN,LGREY,BLACK,LGREY,CYAN,LGREY,LCYAN,LGREY,LCYAN,DRKGRY,
DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY,DRKGRY
)};

inline constexpr screen::Tile tile {
    .side_length = 24,
    .transparent = 0,
    .format = TILE_SCREEN_FORMAT,
    .data = std::data(tile_data)
};

} // namespace

[[nodiscard]] constexpr screen::Tile get_texture() noexcept
{
    return tile;
}

} // namespace chippie::texture::thief
#endif
